# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lw_step": "single_LW_walker.ipynb",
         "lw_trajs": "single_LW_walker.ipynb",
         "get_distance": "single_LW_walker.ipynb",
         "isBetween": "single_LW_walker.ipynb",
         "isBetween_ab_Vec": "single_LW_walker.ipynb",
         "isBetween_c_Vec": "single_LW_walker.ipynb",
         "LW_search": "single_LW_walker.ipynb"}

modules = ["single_LW_walker.py"]

doc_url = "https://gorkamunoz.github.io/rl_optimal_search/"

git_url = "https://github.com/gorkamunoz/rl_optimal_search/tree/master/"

def custom_doc_links(name): return None
