# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lw_step": "diffusion_walks.ipynb",
         "lw_trajs": "diffusion_walks.ipynb",
         "multiexp_dist": "diffusion_walks.ipynb",
         "discrete_multiexp_step": "diffusion_walks.ipynb",
         "get_distance": "environment.ipynb",
         "isBetween": "environment.ipynb",
         "isBetween_ab_Vec": "environment.ipynb",
         "isBetween_c_Vec": "environment.ipynb",
         "is_c_between_ab": "environment.ipynb",
         "target_env": "environment.ipynb",
         "target_search": "environment.ipynb",
         "target_search_onhit": "environment.ipynb"}

modules = ["cluster_launch.py",
           "diffusion_walks.py",
           "environment.py"]

doc_url = "https://gorkamunoz.github.io/rl_optimal_search/"

git_url = "https://github.com/gorkamunoz/rl_optimal_search/tree/master/"

def custom_doc_links(name): return None
