# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['add_colorbar']

# %% ../nbs/utils.ipynb 1
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

def add_colorbar(vec, ax, fig, label):
    normalize = mcolors.Normalize(vmin=vec.min(), vmax=vec.max())
    colormap = plt.cm.plasma
    scalarmappaple = plt.cm.ScalarMappable(norm=normalize, cmap=colormap)
    scalarmappaple.set_array(vec)
    cbar = fig.colorbar(scalarmappaple, ax = ax)
    cbar.set_label(label)
