# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/lib_nbs/12_agents_numba.ipynb.

# %% auto #0
__all__ = ['Forager', 'Foragers', 'Foragers_efficient', 'train_loop_reset', 'run_agents_reset_1D', 'run_agents_reset_2D',
           'train_loop_collective', 'run_collective', 'train_loop_collective_directions', 'run_collective_directions']

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #af595e2e
import numpy as np
from numba.experimental import jitclass
from numba import float64, int64,  njit, prange

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6a5d774a
from ...utils import rand_choice_vectorized, rand_choice_nb

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6d6058bd
@jitclass([("size_state_space", int64[:]),           
           ("initial_prob_distr", float64[:,:]),           
           ("fixed_policy", float64[:,:]) ,
           ("h_matrix", float64[:,:]) ,
           ("g_matrix", float64[:,:]) ,
           ("h_0", float64[:,:]),
           ("prefactor_1", float64[:]),
           ("prefactor_2", float64[:]),
           ("last_upd_G", float64[:,:])
          ])
class Forager():
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_state : int
    size_state_space : np.array
    initial_prob_distr : np.array
    fixed_policy : np.array    
    h_matrix : np.array
    g_matrix : np.array
    h_0 : np.array
    g_update : str
    # Efficient H update
    prefactor_1: np.array
    prefactor_2: np.array
    max_no_H_update : int
    N_upd_H : int
    # Efficient G update
    last_upd_G: np.array
    N_upd_G: int
    
    def __init__(self, 
                 # Number of actions the agent can take
                 num_actions : int, 
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature 
                 size_state_space : np.array, 
                 # Gamma damping from PS
                 gamma_damping=0.0, 
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard', 
                 # Beta parameter for softmax policy
                 beta_softmax=3, 
                 # Initial probability distribution for the H matrix
                 initial_prob_distr = np.array([[],[]]), 
                 # Fixed policy for the agent to follow
                 fixed_policy=np.array([[],[]]),
                 # Max number of steps without updating the H matrix. After this number, the full H matrix is updated
                 max_no_H_update = int(1e4),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 # Works as follows: s (sum) -> g_mat += 1 or r (reset) -> gmat = 1 when updating gmat
                 g_update = 's', 
                ):
        """

        This class defines a Forager agent, able to perform actions and learn from rewards based on the PS paradigm.

        This is an updated version from the one used in the original paper (https://doi.org/10.1088/1367-2630/ad19a8), 
        taking into account the improvements made to the H and G matrices proposed by Michele Caraglio in our paper
        (https://doi.org/10.1039/D3SM01680C).
        """
        
        self.agent_state = 0
        
        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space)) # total number of possible percepts
        
        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.initial_prob_distr = initial_prob_distr
        self.fixed_policy = fixed_policy    
        self.g_update = g_update
        
        self.init_matrices()
        
        # For H update
        self.max_no_H_update = max_no_H_update      
        self.N_upd_H = 0
        self.prefactor_1 = (1-self.gamma_damping)**(np.arange(1,self.max_no_H_update+1)) 
        self.prefactor_2 = np.zeros(self.max_no_H_update)
        for i in range(max_no_H_update):
            self.prefactor_2[i] = self.gamma_damping*np.sum((1-self.gamma_damping)**np.arange(i+1))
            
        # For G update
        self.last_upd_G = np.zeros((self.num_actions, self.num_percepts))
        self.N_upd_G = 0
                              
        
    def init_matrices(self):

        self.g_matrix = np.zeros((self.num_actions, self.num_percepts)) #glow matrix, for processing delayed rewards

        # initialize h matrix with different values
        if len(self.initial_prob_distr[0]) > 0:          
            self.h_0 = self.initial_prob_distr
            self.h_matrix = self.h_0.copy()
        else: 
            self.h_matrix = np.ones((self.num_actions, self.num_percepts), dtype=np.float64) #Note: the first index specifies the action, the second index specifies the percept.
            
    def _learn_post_reward(self, reward):
        '''Given a reward, updates the whole H-matrix taking into account that we did not have updates
        for the last N_upd_H steps.'''
        # Update the full G matrix
        self._G_upd_full()
        
        if self.N_upd_H == 0:
            print('Counter for h_matrix is zero, check that your are properly updating it!')
        if len(self.initial_prob_distr[0]) > 0:
            self.h_matrix = self.prefactor_1[self.N_upd_H-1] * self.h_matrix + self.prefactor_2[self.N_upd_H-1] * self.h_0 + reward * self.g_matrix
        else:
            self.h_matrix = self.prefactor_1[self.N_upd_H-1] * self.h_matrix + self.prefactor_2[self.N_upd_H-1] + reward * self.g_matrix
        self.N_upd_H = 0
        
    def _H_upd_single_percept(self, t, percept):
        '''Given a percept and the time t passed since the last H-matrix update,
        returns the corresponding --updated-- column of the H-matrix for all actions.
        This updated is local and does no affect the H-matrix.'''
        if len(self.initial_prob_distr[0]) > 0:
            return self.prefactor_1[t-1] * self.h_matrix[:, percept] + self.prefactor_2[t-1] * self.h_0[:, percept]
        else:
            return self.prefactor_1[t-1] * self.h_matrix[:, percept] + self.prefactor_2[t-1] 
        
    def _G_upd_single_percept(self, percept, action):
        '''Given a percept-action tuple, updates that element of the G-matrix. Updates the last_upd_G
        to keep track of when was the matrix updated.'''
        
        if self.g_update == 's': # For the current (a,s) tuple, we damp and sum one
            self.g_matrix[action, percept] = (1 - self.eta_glow_damping)**(self.N_upd_G - self.last_upd_G[action, percept])*self.g_matrix[action, percept] + 1
        elif self.g_update == 'r':
            self.g_matrix[action, percept] = 1
        
        # Then update the last_upd matrix
        self.last_upd_G[action, percept] = self.N_upd_G
        
    def _G_upd_full(self):
        '''Given the current number of steps without an update, updates the whole G-matrix.
        Then, resets all counters.'''
        self.g_matrix = (1 - self.eta_glow_damping)**(self.N_upd_G - self.last_upd_G) * self.g_matrix
        self.N_upd_G = 0
        self.last_upd_G = np.zeros((self.num_actions, self.num_percepts))
            
            
    def percept_preprocess(self, observation):
        """
        Takes a multi-feature percept and reduces it to a single integer index.

        Parameters
        ----------
        observation : ARRAY of integers >=0, of the same length as self.num_percepts_list
            List that describes the observation. Each entry is the value that each feature takes in the observation.
            observation[i] < num_percepts_list[i] (strictly)

        Returns
        -------
        percept : int
            Percept index that corresponds to the input observation.

        """
        
        percept = 0
        for idx_obs, obs_feature in enumerate(observation):
            percept += int(obs_feature * np.prod(self.size_state_space[:idx_obs]))  
        return percept
    
    def deliberate(self, observation):
        """
        Given an observation , this method chooses the next action and records that choice in the g_matrix.

        Parameters
        ----------
        observation : list
            List that describes the observation, as specified in percept_preprocess.
        action : optional, bool
            Mostly for debugging, we can input the action and no deliberation takes place, but g_matrix is updated

        Returns
        -------
        action : int
            Index of the chosen action.

        """
        percept = self.percept_preprocess(observation) 
        
        
        # Probabilities must be of update h_matrix. We feed the prob distr the update h_matrix
        # for the percept, but don't update the h_matrix
        if self.N_upd_H == 0:
            current_h_mat = self.h_matrix[:, percept]
        else:
            current_h_mat = self._H_upd_single_percept(self.N_upd_H, percept)
        probs = self.probability_distr(percept, h_matrix = current_h_mat)        
        action = rand_choice_nb(arr = np.arange(self.num_actions), prob = probs)
        
        # Update the G matrix for current (s,a) tuple
        self._G_upd_single_percept(percept, action)
        
        return action
    
    def probability_distr(self, percept, h_matrix = None):
        """
        UPDATE (added the optional input)
         
        Given a percept index, this method returns a probability distribution over actions.

        Parameters
        ----------
        percept : int
            Index of the given percept.

        Returns
        -------
        probability_distr : np.array, length = num_actions
            Probability for each action (normalized to unit sum), computed according to policy_type.

        """
        
        if self.policy_type == 'standard':
            h_vector = self.h_matrix[:, percept] if h_matrix is None else h_matrix
            probability_distr = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            h_vector = self.beta_softmax * self.h_matrix[:, percept] if h_matrix is None else h_matrix
            h_vector_mod = h_vector - np.max(h_vector)
            probability_distr = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))
        return probability_distr
    
    def learn(self, reward):
        """
        Given a reward, this method updates the h matrix.

        Parameters
        ----------
        reward : float
            Value of the obtained reward.
        """
        if len(self.initial_prob_distr[0]) > 0:
            self.h_matrix =  self.h_matrix - self.gamma_damping * (self.h_matrix - self.h_0) + reward * self.g_matrix
        else:
            self.h_matrix =  self.h_matrix - self.gamma_damping * (self.h_matrix - 1.) + reward * self.g_matrix
            
    def reset_g(self):
        """
        Resets the g_matrix.
        """
        self.g_matrix = np.zeros((self.num_actions, self.num_percepts), dtype=np.float64)
        
    def deliberate_fixed_policy(self, observation):
        """
        Given an observation , this method chooses the next action according to the fixed policy specified as attribute of the class.

        Parameters
        ----------
        observation : list
            List that describes the observation, as specified in percept_preprocess.

        Returns
        -------
        action : int
            Index of the chosen action.

        """
        percept = self.percept_preprocess(observation) 
        if len(self.fixed_policy[0]) > 0:
            action = rand_choice_nb(arr = np.arange(self.num_actions), prob = self.fixed_policy[percept])
        else:
            print('No fixed policy was given to the agent. The action will be selected randomly.')
            action = np.random.choice(self.num_actions)
    
        self.g_matrix = (1 - self.eta_glow_damping) * self.g_matrix
        self.g_matrix[action, percept] += 1 #record latest decision in g_matrix
    
        return action
    
    def act(self, action):
        """
        Agent performs the given action.

        Parameters
        ----------
        action : int (0, 1)
            1 if it changes direction, 0 otherwise
        """
        
        # If the agent changes direction   
        if action == 1:
            self.agent_state = 0
        else:
            self.agent_state += 1  
            
    
    def get_state(self):  
        ''' simplified to case of single forager. Returns list because is what deliberate needs'''
        return np.array([self.agent_state])

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #ebf9d445
@jitclass([("agent_states", int64[:]), 
           ("size_state_space", int64[:]),  
           ("h_matrix", float64[:,:,:]) ,
           ("g_matrix", float64[:,:,:]) ,
           ("h_0", float64[:,:,:]),
          ])
class Foragers():
    num_agents : int
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_states: np.ndarray
    size_state_space: np.ndarray
    initial_h_0: bool
    h_matrix: np.ndarray
    g_matrix: np.ndarray
    h_0: np.ndarray
    g_update : str
    
    def __init__(self, 
                 # Number of agents,
                 num_agents : int,
                 # Number of actions the agent can take
                 num_actions : int, 
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature 
                 size_state_space : np.ndarray, 
                 # Gamma damping from PS
                 gamma_damping=0.0, 
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard', 
                 # Beta parameter for softmax policy
                 beta_softmax=3, 
                 # If to consider initial probability distribution for the H matrix or not. 
                 initial_h_0 = False,
                 # value of initial h_matrix
                 h_0 = np.array([[[],[],[]]]),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 # Works as follows: s (sum) -> g_mat += 1 or r (reset) -> gmat = 1 when updating gmat
                 g_update = 's', 
                ):
        """

        This class defines a Foragers agent, an extension of the Forager class to multi agent scenarios efficiently.
        """
        self.num_agents = num_agents

        self.agent_states = np.zeros(num_agents, dtype=np.int64)
        
        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space)) # total number of possible percepts
        
        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.g_update = g_update
      
        self.initial_h_0 = initial_h_0
        self.h_0 = h_0
        
        self.init_matrices()        

    def reset_g(self):
        """
        Resets the g_matrix.
        """
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)                          
        
    def init_matrices(self):

        self.reset_g()

        # initialize h matrix with different values
        if self.initial_h_0: 
            self.h_matrix = self.h_0.copy()
        else: 
            self.h_matrix = np.ones((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64) #Note: the first index specifies the action, the second index specifies the percept.
            
    def learn(self, rewards):
        """
        Given rewards, this method updates the h matrix.

        Parameters
        ----------
        rewards : array of floats, shape (num_agents,)
            Values of the obtained rewards for each agent.
        """
        if self.initial_h_0: 
            self.h_matrix = self.h_matrix - self.gamma_damping * (self.h_matrix - self.h_0) + rewards[:, None, None] * self.g_matrix
        else:
            self.h_matrix = self.h_matrix - self.gamma_damping * (self.h_matrix - 1.) + rewards[:, None, None] * self.g_matrix      
            
    def percept_preprocess(self, observations):
        """
        Takes a multi-feature percept and reduces it to a single integer index.

        Parameters
        ----------
        observations : array of FLOAT&$ (!!!) >=0, of the same length as self.num_percepts_list
            List that describes the observation. Each entry is the value that each feature takes in the observation.
            observation[i] < num_percepts_list[i] (strictly)

        Returns
        -------
        percept : int
            Percept index that corresponds to the input observation.

        """

        # Compute the cumulative product of the state space dimensions
        state_space_factors = np.zeros(len(self.size_state_space))
        state_space_factors[0] = 1
        state_space_factors[1:] = np.cumprod(self.size_state_space[:-1])

        # Use matrix multiplication to compute percepts for all agents
        percepts = np.dot(observations, state_space_factors)

        return percepts.astype(np.int64)  # Ensure the output is of integer type
    
    def deliberate(self, observations):
        """
        Given an observation , this method chooses the next action and records that choice in the g_matrix.

        Parameters
        ----------
        observations : array of observations, shape (num_agents, num_features)
        action : optional, bool
            Mostly for debugging, we can input the action and no deliberation takes place, but g_matrix is updated

        Returns
        -------
        actions : array
            Containing the action of each agent.

        """
        percepts = self.percept_preprocess(observations) 

        probs = self.probability_distr(percepts)
     
        actions = rand_choice_vectorized(probs = probs)  

        self.g_matrix = (1 - self.eta_glow_damping) * self.g_matrix
        # Loop-based approach to update g_matrix
        for i in range(self.num_agents):
            self.g_matrix[i, actions[i], percepts[i]] += 1  # Update the corresponding element
        
        return actions
    
    def probability_distr(self, percepts):
        """
         
        Given a percept index, this method returns a probability distribution over actions.

        Parameters
        ----------
        percepts : array of ints
            Indices of the given percepts.

        Returns
        -------
        probability_distr : np.array, length = num_actions
            Probability for each action (normalized to unit sum), computed according to policy_type.

        """

        # No Numba version of standard (for reference):
        # # Extract h_matrix for all agents and the given percept
        # h_vectors = self.h_matrix[np.arange(self.num_agents), :, percepts] 
        # # Compute probability distribution for all agents
        # probability_distr = h_vectors / np.sum(h_vectors, axis=1, keepdims=True)  

        # Preallocate the result array
        probability_distr = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            # Loop over agents to extract h_vectors and compute probabilities
            for i in range(self.num_agents):
                h_vector = self.h_matrix[i, :, percepts[i]]
                probability_distr[i, :] = h_vector / np.sum(h_vector)

        elif self.policy_type == 'softmax':
            # Loop over agents to extract h_vectors and compute softmax probabilities
            for i in range(self.num_agents):
                h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                h_vector_mod = h_vector - np.max(h_vector)  # Stabilize softmax
                probability_distr[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        return probability_distr       
    
       
    
    def act(self, actions):
        """
        Agent performs the given actions.

        Parameters
        ----------
        actions : array of ints (0, 1)
            1 if it changes direction, 0 otherwise
        """
        
        # If the agent changes direction   
        self.agent_states[actions == 1] = 0
        self.agent_states[actions == 0] += 1
            
    
    def get_state(self):  
        ''' Returns the counter of all agents in the form of arra'''
        return self.agent_states

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #613a24f0
@jitclass([("agent_states", int64[:]),
           ("size_state_space", int64[:]),
           ("h_matrix", float64[:,:,:]),
           ("g_matrix", float64[:,:,:]),
           ("h_0", float64[:,:,:]),
           ("prefactor_1", float64[:]),
           ("prefactor_2", float64[:]),
           ("last_upd_G", float64[:,:,:]),
           ("N_upd_H", int64[:]),
           ("N_upd_G", int64[:]),
           ("state_space_factors", float64[:])
          ])
class Foragers_efficient():
    num_agents : int
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_states: np.ndarray
    size_state_space: np.ndarray
    initial_h_0: bool
    h_matrix: np.ndarray
    g_matrix: np.ndarray
    h_0: np.ndarray
    g_update : str
    state_space_factors : np.ndarray
    # Efficient H update
    prefactor_1: np.ndarray
    prefactor_2: np.ndarray
    max_no_H_update : int
    N_upd_H : np.ndarray
    # Efficient G update
    last_upd_G: np.ndarray
    N_upd_G: np.ndarray

    def __init__(self,
                 # Number of agents
                 num_agents : int,
                 # Number of actions the agent can take
                 num_actions : int,
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature
                 size_state_space : np.ndarray,
                 # Gamma damping from PS
                 gamma_damping=0.0,
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard',
                 # Beta parameter for softmax policy
                 beta_softmax=3,
                 # If to consider initial probability distribution for the H matrix or not.
                 initial_h_0=False,
                 # value of initial h_matrix
                 h_0=np.array([[[],[],[]]]),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 g_update='s',
                 # Max number of steps without updating the H matrix
                 max_no_H_update=int(1e4),
                ):
        """
        Efficient version of Foragers. Uses lazy H-matrix and G-matrix updates
        (only on reward or when max_no_H_update is reached), following the same
        strategy as the single-agent Forager class.

        Key differences vs Foragers:
          - H-matrix is NOT updated every step. Instead, prefactors are used to
            compute the virtually-updated H column on the fly in deliberate().
          - G-matrix updates are lazy: only the (agent, action, percept) entry
            touched during deliberate() is updated; the rest are deferred.
          - _learn_post_reward(rewards) replaces learn(rewards). It flushes the
            pending G-matrix decays and applies the accumulated H-matrix damping
            for each agent that received a reward (or hit max_no_H_update).
        """
        self.num_agents = num_agents
        self.agent_states = np.zeros(num_agents, dtype=np.int64)

        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space))

        # precompute factors for percept_preprocess
        self.state_space_factors = np.zeros(len(self.size_state_space), dtype=np.float64)
        self.state_space_factors[0] = 1
        self.state_space_factors[1:] = np.ascontiguousarray(np.cumprod(self.size_state_space[:-1]))

        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.g_update = g_update

        self.initial_h_0 = initial_h_0
        self.h_0 = h_0

        self.init_matrices()

        # Efficient H update prefactors (same as Forager)
        self.max_no_H_update = max_no_H_update
        self.N_upd_H = np.zeros(num_agents, dtype=np.int64)
        self.prefactor_1 = (1 - self.gamma_damping) ** np.arange(1, self.max_no_H_update + 1)
        self.prefactor_2 = np.zeros(self.max_no_H_update)
        for i in range(max_no_H_update):
            self.prefactor_2[i] = self.gamma_damping * np.sum(
                (1 - self.gamma_damping) ** np.arange(i + 1)
            )

        # Efficient G update tracking (per-agent)
        self.N_upd_G = np.zeros(num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((num_agents, self.num_actions, self.num_percepts))

    def init_matrices(self):
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        if self.initial_h_0:
            self.h_matrix = self.h_0.copy()
        else:
            self.h_matrix = np.ones((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)

    def reset_g(self):
        """Resets g_matrix and all update counters (H and G)."""
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        self.N_upd_H = np.zeros(self.num_agents, dtype=np.int64)
        self.N_upd_G = np.zeros(self.num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((self.num_agents, self.num_actions, self.num_percepts))

    def increment_counters(self):
        """Increment N_upd_H and N_upd_G for all agents. Call at start of each timestep."""
        for i in range(self.num_agents):
            self.N_upd_H[i] += 1
            self.N_upd_G[i] += 1

    # ── Efficient G-matrix updates ────────────────────────────────────────

    def _G_upd_single_percept(self, agent_idx, percept, action):
        """Lazily update G for a single (agent, action, percept) tuple."""
        if self.g_update == 's':
            decay = (1 - self.eta_glow_damping) ** (
                self.N_upd_G[agent_idx] - self.last_upd_G[agent_idx, action, percept]
            )
            self.g_matrix[agent_idx, action, percept] = (
                decay * self.g_matrix[agent_idx, action, percept] + 1
            )
        elif self.g_update == 'r':
            self.g_matrix[agent_idx, action, percept] = 1
        self.last_upd_G[agent_idx, action, percept] = self.N_upd_G[agent_idx]

    def _G_upd_full(self, agent_idx):
        """Apply all pending G-matrix decays for one agent, then reset its counters."""
        n = self.N_upd_G[agent_idx]
        for a in range(self.num_actions):
            for p in range(self.num_percepts):
                self.g_matrix[agent_idx, a, p] *= (
                    (1 - self.eta_glow_damping) ** (n - self.last_upd_G[agent_idx, a, p])
                )
                self.last_upd_G[agent_idx, a, p] = 0.0
        self.N_upd_G[agent_idx] = 0

    # ── Efficient H-matrix updates ────────────────────────────────────────

    def _H_upd_single_percept(self, agent_idx, t, percept):
        """Return the virtually-updated h_matrix column for one agent/percept
        without modifying h_matrix."""
        if self.initial_h_0:
            return (self.prefactor_1[t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[t - 1] * self.h_0[agent_idx, :, percept])
        else:
            return (self.prefactor_1[t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[t - 1])

    def _learn_post_reward(self, rewards):
        """Update H (and flush G) for each agent that received a reward or hit max_no_H_update.
        
        Parameters
        ----------
        rewards : array of floats, shape (num_agents,)
        """
        for i in range(self.num_agents):
            if rewards[i] > 0 or self.N_upd_H[i] >= self.max_no_H_update - 1:
                if self.N_upd_H[i] == 0:
                    continue
                self._G_upd_full(i)
                if self.initial_h_0:
                    self.h_matrix[i] = (
                        self.prefactor_1[self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[self.N_upd_H[i] - 1] * self.h_0[i]
                        + rewards[i] * self.g_matrix[i]
                    )
                else:
                    self.h_matrix[i] = (
                        self.prefactor_1[self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[self.N_upd_H[i] - 1]
                        + rewards[i] * self.g_matrix[i]
                    )
                self.N_upd_H[i] = 0

    # ── Percept preprocessing ─────────────────────────────────────────────

    def percept_preprocess(self, observations):
        """Same as Foragers.percept_preprocess."""
        
        percepts = np.dot(observations, np.ascontiguousarray(self.state_space_factors))
        return percepts.astype(np.int64)

    # ── Deliberation ──────────────────────────────────────────────────────

    def deliberate(self, observations):
        """
        Like Foragers.deliberate but uses efficient H lookup and lazy G update.
        """
        percepts = self.percept_preprocess(observations)

        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        actions = rand_choice_vectorized(probs=probs)

        for i in range(self.num_agents):
            self._G_upd_single_percept(i, percepts[i], actions[i])

        return actions

    def probability_distr(self, percepts):
        """Like Foragers.probability_distr but uses efficient H lookup."""
        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        return probs

    # ── Action & state ────────────────────────────────────────────────────

    def act(self, actions):
        """Same as Foragers.act."""
        self.agent_states[actions == 1] = 0
        self.agent_states[actions == 0] += 1

    def get_state(self):
        """Same as Foragers.get_state."""
        return self.agent_states

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #dbfcbdf9
@njit
def train_loop_reset(episodes, time_ep, agent, env, h_mat_allT = False, when_save_h_mat = 1, reset_after_reward = True):  

    if h_mat_allT: 
        policy_t = np.zeros((int(np.ceil(episodes/when_save_h_mat)), 
                             agent.h_matrix.shape[-1]))
        idx_policy_save = 0
        
    save_rewards = np.zeros(episodes)
    
    for ep in range(episodes):
        
        #initialize environment and agent's counter and g matrix
        env.init_env()
        agent.agent_state = 0
        agent.reset_g()

        for t in range(time_ep):
            agent.N_upd_H += 1
            agent.N_upd_G += 1

            #get perception
            state = agent.get_state()
            
            # if we reached the maximum state space, we perform turn action
            if state == agent.h_matrix.shape[-1]:
                action = 1
            # else we do as normal    
            else: 
                action = agent.deliberate(state)
                
            #act (update counter)
            agent.act(action)

            #update positions
            reward = env.update_pos(action)            

            if reward == 1 or agent.N_upd_H == agent.max_no_H_update-1:
                agent._learn_post_reward(reward)
            
            if reset_after_reward == True and reward != 0:
                agent.agent_state = 0

            # Saving
            save_rewards[ep] += reward
        if h_mat_allT and ep % when_save_h_mat == 0:
            policy_t[idx_policy_save] = agent.h_matrix[0,:] / agent.h_matrix.sum(0)
            idx_policy_save += 1
      
    return (save_rewards/time_ep, policy_t) if h_mat_allT else (save_rewards/time_ep, agent.h_matrix)

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6a1927d1
from .environments import ResetEnv_1D



@njit(parallel = True)
def run_agents_reset_1D(episodes, time_ep, N_agents,
                       # Environment props
                       D = 1/2, L = 10.0, 
                       # Agent props
                       num_actions = 2,
                       size_state_space = np.array([100]),
                       gamma_damping = 0.00001,
                       eta_glow_damping = 0.1,
                       g_update = 's',
                       initial_prob_distr = np.array([[],[]]),
                       policy_type = 'standard', 
                       beta_softmax = 3,  
                       fixed_policy = np.array([[],[]]),
                       max_no_H_update = int(1e3),
                       h_mat_allT = False, 
                       reset_after_reward = True,
                       # When we want N_agent != number of max cores, we use this to make few runs
                       # over the selected number of cores, given by N_agents.
                       num_runs = None 
                      ):

    if num_runs is None:
        total_agents = N_agents
    else:
        total_agents = N_agents*num_runs
    
    save_rewards = np.zeros((total_agents, episodes))
    if h_mat_allT:
        save_h_matrix = np.zeros((total_agents, episodes, size_state_space.prod()))  
    else:        
        save_h_matrix = np.zeros((total_agents, 2, size_state_space.prod())) 

    # if N_agents is an integer, we consider that we run this at full cores
    if num_runs is None:
    
        for n_agent in prange(N_agents):
            
            agent = Forager(num_actions, size_state_space,
                                      gamma_damping, eta_glow_damping, 
                                      policy_type, beta_softmax,
                                      initial_prob_distr,fixed_policy,max_no_H_update,g_update)
            env = ResetEnv_1D(L, D)
            
            rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
     
            # print(rews.shape, rews[0], rews[0].dtype)
            
            save_rewards[n_agent] = rews
            save_h_matrix[n_agent] = mat

    # If it is a list, the first number is the number of parallel agents and the second the 
    # times we run those parallel agents
    else:

        n_run = -1        
        for run in range(num_runs):
            n_run += 1
            for idxa in prange(N_agents):
            
                agent = Forager(num_actions, size_state_space,
                                gamma_damping, eta_glow_damping, 
                                policy_type, beta_softmax,
                                initial_prob_distr,fixed_policy,max_no_H_update, g_update)
                env = ResetEnv_1D(L, D)
                
                rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
                         
                save_rewards[idxa*num_runs+n_run] = rews
                save_h_matrix[idxa*num_runs+n_run] = mat
        
        
    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #53149e60
from .environments import ResetEnv_2D


@njit(parallel = True)
def run_agents_reset_2D(episodes, time_ep, N_agents,
                     # Environment props
                     dist_target = 10.0, radius_target = 1.0, D = 1/2,
                     # Agent props
                     num_actions = 2,
                     size_state_space = np.array([100]),
                     gamma_damping = 0.00001,
                     eta_glow_damping = 0.1,
                     initial_prob_distr = np.array([[],[]]),
                     policy_type = 'standard', 
                     beta_softmax = 3,  
                     fixed_policy = np.array([[],[]]),
                     max_no_H_update = int(1e3),
                     h_mat_allT = False, when_save_h_mat = 1,
                     reset_after_reward = True,
                     g_update = 's',
                    # When we want N_agent != number of max cores, we use this to make few runs
                    # over the selected number of cores, given by N_agents.
                    num_runs = None                         
                      ):
    
    save_rewards = np.zeros((N_agents, episodes))
    if h_mat_allT:
        save_h_matrix = np.zeros((N_agents, 
                                  int(np.ceil(episodes/when_save_h_mat)), 
                                  size_state_space.prod()))  
    else:        
        save_h_matrix = np.zeros((N_agents, 2, size_state_space.prod())) 

    # if N_agents is an integer, we consider that we run this at full cores
    if num_runs is None:
    
        for n_agent in prange(N_agents):
            
            agent = Forager(num_actions, size_state_space,
                            gamma_damping, eta_glow_damping, 
                            policy_type, beta_softmax,
                            initial_prob_distr,fixed_policy,max_no_H_update,g_update)
            
            env = ResetEnv_2D(dist_target, radius_target, D)
            
            rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, when_save_h_mat, reset_after_reward)            
    
        
            save_rewards[n_agent] = rews
            save_h_matrix[n_agent] = mat

    # If it is a list, the first number is the number of parallel agents and the second the 
    # times we run those parallel agents
    else:

        n_run = -1        
        for run in range(num_runs):
            n_run += 1
            for idxa in prange(N_agents):
            
                agent = Forager(num_actions, size_state_space,
                                gamma_damping, eta_glow_damping, 
                                policy_type, beta_softmax,
                                initial_prob_distr,fixed_policy,max_no_H_update, g_update)
                env = ResetEnv_2D(dist_target, radius_target, D)
                
                rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
                         
                save_rewards[idxa*num_runs+n_run] = rews
                save_h_matrix[idxa*num_runs+n_run] = mat
        
    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #441c899b
@njit
def train_loop_collective(episodes, time_ep, env, agents, max_counter, visual_activated = False, upd_pos_method = 'RND'):
    """
    EXP 5: Target-finding reward with 3D state = [counter, any_agent_in_cone, rewarded_agent_in_cone].

    Uses Foragers_efficient with lazy G updates.
    state_space should be np.array([max_counter, 2, 2]).
    """
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()
        
        # Debugging
        # positions = np.zeros((time_ep, env.num_agents, 2))

        for t in range(time_ep):
            agents.increment_counters()

            # --- Build observations ---
            # 1) Counter (clipped)
            counters = np.minimum(agents.get_state().copy(), np.int64(max_counter - 1))

            # 2) Cone features
            if visual_activated:
                _, agents_spot = env.agents_in_cone()
                # agents_spot is (num_agents, num_agents) with 1 if j is in i's cone

            # any_agent_in_cone: 1 if row sum > 0
            any_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated:
                for i in range(agents.num_agents):
                    if agents_spot[i].sum() > 0:
                        any_in_cone[i] = 1.0

            # rewarded_agent_in_cone: 1 if any agent with rewarded_agents==1 is in cone
            rewarded_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated: 
                for i in range(agents.num_agents):
                    for j in range(agents.num_agents):
                        if agents_spot[i, j] == 1 and env.rewarded_agents[j] == 1:
                            rewarded_in_cone[i] = 1.0
                            break

            # observations shape: (num_agents, 3)
            observations = np.empty((agents.num_agents, 3), dtype=np.float64)
            observations[:, 0] = counters.astype(np.float64)
            observations[:, 1] = any_in_cone
            observations[:, 2] = rewarded_in_cone

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset counter BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step
            if upd_pos_method == 'RND':
                env.update_pos(actions == 1)
            elif upd_pos_method == 'LR':
                env.update_pos(actions)                
            env.check_bc()
            env.update_target_state()
            env.update_rewarded_agents()

            rewards = env.check_encounter()
            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1
        
        # Debugging
        #     positions[t] = env.positions
        # for p in positions.transpose(1, 0, 2):
        #     plt.plot(p[:, 0], p[:, 1], '-')
        # plt.show()

    return save_rewards, agents.h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #0965b580
from .environments import CollectiveEnv

@njit(parallel=True)
def run_collective(episodes, time_ep, runs,
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated = True,
             # Agent props
             num_actions=2,
             state_space=np.array([50, 2, 2]),
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method = 'RND', # Method to update position. 'RND' for random angle turns, 'LR' for left/right turns.
             turn_angle = np.pi/4 # Angle for left/right turns if upd_pos_method is 'LR'.
             ):
    """
    Parallel launcher for collective training, where visual features are 
    if yes/no seeing an agent in front and if yes/no seeing a rewarded agent in front:
    
    state_space = np.array([max_counter, 2, 2])
    """
    save_h_matrix = np.zeros((runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((runs, num_agents, episodes))

    for n_run in prange(runs):
        agents = Foragers_efficient(
            num_agents, num_actions, state_space,
            gamma_damping, eta_glow_damping, policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )
        env = CollectiveEnv(num_agents, Nt, L, r, tau, agent_step,
                            visual_range, visual_angle, shared_depletion, tau_reward, upd_pos_method, turn_angle)

        rews, mat = train_loop_collective(episodes, time_ep, env, agents, state_space[0], visual_activated, upd_pos_method)

        for t in range(episodes):
            save_rewards[n_run, :, t] = rews[:, t]
        save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #54bdabfe
@njit
def train_loop_collective_directions(episodes, time_ep, env, agents, max_counter, visual_activated = False, upd_pos_method = 'RND'):
    """
    EXP 5: Target-finding reward with 3D state = [counter, any_agent_in_cone, rewarded_agent_in_cone].

    Uses Foragers_efficient with lazy G updates.
    state_space should be np.array([max_counter, 2, 2]).
    """
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()
        
        # Debugging
        # positions = np.zeros((time_ep, env.num_agents, 2))

        for t in range(time_ep):
            agents.increment_counters()

            # --- Build observations ---
            # 1) Counter (clipped)
            counters = np.minimum(agents.get_state().copy(), np.int64(max_counter - 1))

            # 2) Cone features
            if visual_activated:
                _, agents_spot = env.agents_in_cone()
                # agents_spot is (num_agents, num_agents) with 1 if j is in i's cone

            # any_agent_in_cone: 1 if row sum > 0
            any_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated:
                for i in range(agents.num_agents):
                    if agents_spot[i].sum() > 0:
                        any_in_cone[i] = 1.0

            # rewarded_agent_in_cone: 1 if any agent with rewarded_agents==1 is in cone
            rewarded_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated: 
                for i in range(agents.num_agents):
                    for j in range(agents.num_agents):
                        if agents_spot[i, j] == 1 and env.rewarded_agents[j] == 1:
                            rewarded_in_cone[i] = 1.0
                            break

            # observations shape: (num_agents, 3)
            observations = np.empty((agents.num_agents, 3), dtype=np.float64)
            observations[:, 0] = counters.astype(np.float64)
            observations[:, 1] = any_in_cone
            observations[:, 2] = rewarded_in_cone

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset counter BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step
            if upd_pos_method == 'RND':
                env.update_pos(actions == 1)
            elif upd_pos_method == 'LR':
                env.update_pos(actions)                
            env.check_bc()
            env.update_target_state()
            env.update_rewarded_agents()

            rewards = env.check_encounter()
            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1
        
        # Debugging
        #     positions[t] = env.positions
        # for p in positions.transpose(1, 0, 2):
        #     plt.plot(p[:, 0], p[:, 1], '-')
        # plt.show()

    return save_rewards, agents.h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #70e90cb8
from .environments import CollectiveEnv

@njit(parallel=True)
def run_collective_directions(episodes, time_ep, runs,
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated = True,
             # Agent props
             num_actions=2,
             state_space=np.array([50, 2, 2]),
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method = 'RND', # Method to update position. 'RND' for random angle turns, 'LR' for left/right turns.
             turn_angle = np.pi/4 # Angle for left/right turns if upd_pos_method is 'LR'.
             ):
    """
    Parallel launcher for collective training, where visual features are 
    if yes/no seeing an agent in front and if yes/no seeing a rewarded agent in front:
    
    state_space = np.array([max_counter, 2, 2])
    """
    save_h_matrix = np.zeros((runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((runs, num_agents, episodes))

    for n_run in prange(runs):
        agents = Foragers_efficient(
            num_agents, num_actions, state_space,
            gamma_damping, eta_glow_damping, policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )
        env = CollectiveEnv(num_agents, Nt, L, r, tau, agent_step,
                            visual_range, visual_angle, shared_depletion, tau_reward, upd_pos_method, turn_angle)

        rews, mat = train_loop_collective(episodes, time_ep, env, agents, state_space[0], visual_activated, upd_pos_method)

        for t in range(episodes):
            save_rewards[n_run, :, t] = rews[:, t]
        save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix
