# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/lib_nbs/12_agents_numba.ipynb.

# %% auto #0
__all__ = ['Forager', 'Foragers', 'Foragers_efficient', 'Foragers_efficient_ind', 'train_loop_reset', 'run_agents_reset_1D',
           'run_agents_reset_2D', 'train_loop_collective', 'run_collective', 'run_collective_dict',
           'run_collect_dict_ind', 'train_loop_collective_directions', 'run_collective_directions',
           'train_loop_follow_directions', 'run_follow_directions', 'train_loop_collective_target_visual',
           'run_collective_target_visual']

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #af595e2e
import numpy as np
from numba.experimental import jitclass
from numba import float64, int64, boolean, njit, prange

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6a5d774a
from ...utils import rand_choice_vectorized, rand_choice_nb

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6d6058bd
@jitclass([("size_state_space", int64[:]),           
           ("initial_prob_distr", float64[:,:]),           
           ("fixed_policy", float64[:,:]) ,
           ("h_matrix", float64[:,:]) ,
           ("g_matrix", float64[:,:]) ,
           ("h_0", float64[:,:]),
           ("prefactor_1", float64[:]),
           ("prefactor_2", float64[:]),
           ("last_upd_G", float64[:,:])
          ])
class Forager():
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_state : int
    size_state_space : np.array
    initial_prob_distr : np.array
    fixed_policy : np.array    
    h_matrix : np.array
    g_matrix : np.array
    h_0 : np.array
    g_update : str
    # Efficient H update
    prefactor_1: np.array
    prefactor_2: np.array
    max_no_H_update : int
    N_upd_H : int
    # Efficient G update
    last_upd_G: np.array
    N_upd_G: int
    
    def __init__(self, 
                 # Number of actions the agent can take
                 num_actions : int, 
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature 
                 size_state_space : np.array, 
                 # Gamma damping from PS
                 gamma_damping=0.0, 
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard', 
                 # Beta parameter for softmax policy
                 beta_softmax=3, 
                 # Initial probability distribution for the H matrix
                 initial_prob_distr = np.array([[],[]]), 
                 # Fixed policy for the agent to follow
                 fixed_policy=np.array([[],[]]),
                 # Max number of steps without updating the H matrix. After this number, the full H matrix is updated
                 max_no_H_update = int(1e4),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 # Works as follows: s (sum) -> g_mat += 1 or r (reset) -> gmat = 1 when updating gmat
                 g_update = 's', 
                ):
        """

        This class defines a Forager agent, able to perform actions and learn from rewards based on the PS paradigm.

        This is an updated version from the one used in the original paper (https://doi.org/10.1088/1367-2630/ad19a8), 
        taking into account the improvements made to the H and G matrices proposed by Michele Caraglio in our paper
        (https://doi.org/10.1039/D3SM01680C).
        """
        
        self.agent_state = 0
        
        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space)) # total number of possible percepts
        
        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.initial_prob_distr = initial_prob_distr
        self.fixed_policy = fixed_policy    
        self.g_update = g_update
        
        self.init_matrices()
        
        # For H update
        self.max_no_H_update = max_no_H_update      
        self.N_upd_H = 0
        self.prefactor_1 = (1-self.gamma_damping)**(np.arange(1,self.max_no_H_update+1)) 
        self.prefactor_2 = np.zeros(self.max_no_H_update)
        for i in range(max_no_H_update):
            self.prefactor_2[i] = self.gamma_damping*np.sum((1-self.gamma_damping)**np.arange(i+1))
            
        # For G update
        self.last_upd_G = np.zeros((self.num_actions, self.num_percepts))
        self.N_upd_G = 0
                              
        
    def init_matrices(self):

        self.g_matrix = np.zeros((self.num_actions, self.num_percepts)) #glow matrix, for processing delayed rewards

        # initialize h matrix with different values
        if len(self.initial_prob_distr[0]) > 0:          
            self.h_0 = self.initial_prob_distr
            self.h_matrix = self.h_0.copy()
        else: 
            self.h_matrix = np.ones((self.num_actions, self.num_percepts), dtype=np.float64) #Note: the first index specifies the action, the second index specifies the percept.
            
    def _learn_post_reward(self, reward):
        '''Given a reward, updates the whole H-matrix taking into account that we did not have updates
        for the last N_upd_H steps.'''
        # Update the full G matrix
        self._G_upd_full()
        
        if self.N_upd_H == 0:
            print('Counter for h_matrix is zero, check that your are properly updating it!')
        if len(self.initial_prob_distr[0]) > 0:
            self.h_matrix = self.prefactor_1[self.N_upd_H-1] * self.h_matrix + self.prefactor_2[self.N_upd_H-1] * self.h_0 + reward * self.g_matrix
        else:
            self.h_matrix = self.prefactor_1[self.N_upd_H-1] * self.h_matrix + self.prefactor_2[self.N_upd_H-1] + reward * self.g_matrix
        self.N_upd_H = 0
        
    def _H_upd_single_percept(self, t, percept):
        '''Given a percept and the time t passed since the last H-matrix update,
        returns the corresponding --updated-- column of the H-matrix for all actions.
        This updated is local and does no affect the H-matrix.'''
        if len(self.initial_prob_distr[0]) > 0:
            return self.prefactor_1[t-1] * self.h_matrix[:, percept] + self.prefactor_2[t-1] * self.h_0[:, percept]
        else:
            return self.prefactor_1[t-1] * self.h_matrix[:, percept] + self.prefactor_2[t-1] 
        
    def _G_upd_single_percept(self, percept, action):
        '''Given a percept-action tuple, updates that element of the G-matrix. Updates the last_upd_G
        to keep track of when was the matrix updated.'''
        
        if self.g_update == 's': # For the current (a,s) tuple, we damp and sum one
            self.g_matrix[action, percept] = (1 - self.eta_glow_damping)**(self.N_upd_G - self.last_upd_G[action, percept])*self.g_matrix[action, percept] + 1
        elif self.g_update == 'r':
            self.g_matrix[action, percept] = 1
        
        # Then update the last_upd matrix
        self.last_upd_G[action, percept] = self.N_upd_G
        
    def _G_upd_full(self):
        '''Given the current number of steps without an update, updates the whole G-matrix.
        Then, resets all counters.'''
        self.g_matrix = (1 - self.eta_glow_damping)**(self.N_upd_G - self.last_upd_G) * self.g_matrix
        self.N_upd_G = 0
        self.last_upd_G = np.zeros((self.num_actions, self.num_percepts))
            
            
    def percept_preprocess(self, observation):
        """
        Takes a multi-feature percept and reduces it to a single integer index.

        Parameters
        ----------
        observation : ARRAY of integers >=0, of the same length as self.num_percepts_list
            List that describes the observation. Each entry is the value that each feature takes in the observation.
            observation[i] < num_percepts_list[i] (strictly)

        Returns
        -------
        percept : int
            Percept index that corresponds to the input observation.

        """
        
        percept = 0
        for idx_obs, obs_feature in enumerate(observation):
            percept += int(obs_feature * np.prod(self.size_state_space[:idx_obs]))  
        return percept
    
    def deliberate(self, observation):
        """
        Given an observation , this method chooses the next action and records that choice in the g_matrix.

        Parameters
        ----------
        observation : list
            List that describes the observation, as specified in percept_preprocess.
        action : optional, bool
            Mostly for debugging, we can input the action and no deliberation takes place, but g_matrix is updated

        Returns
        -------
        action : int
            Index of the chosen action.

        """
        percept = self.percept_preprocess(observation) 
        
        
        # Probabilities must be of update h_matrix. We feed the prob distr the update h_matrix
        # for the percept, but don't update the h_matrix
        if self.N_upd_H == 0:
            current_h_mat = self.h_matrix[:, percept]
        else:
            current_h_mat = self._H_upd_single_percept(self.N_upd_H, percept)
        probs = self.probability_distr(percept, h_matrix = current_h_mat)        
        action = rand_choice_nb(arr = np.arange(self.num_actions), prob = probs)
        
        # Update the G matrix for current (s,a) tuple
        self._G_upd_single_percept(percept, action)
        
        return action
    
    def probability_distr(self, percept, h_matrix = None):
        """
        UPDATE (added the optional input)
         
        Given a percept index, this method returns a probability distribution over actions.

        Parameters
        ----------
        percept : int
            Index of the given percept.

        Returns
        -------
        probability_distr : np.array, length = num_actions
            Probability for each action (normalized to unit sum), computed according to policy_type.

        """
        
        if self.policy_type == 'standard':
            h_vector = self.h_matrix[:, percept] if h_matrix is None else h_matrix
            probability_distr = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            h_vector = self.beta_softmax * self.h_matrix[:, percept] if h_matrix is None else h_matrix
            h_vector_mod = h_vector - np.max(h_vector)
            probability_distr = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))
        return probability_distr
    
    def learn(self, reward):
        """
        Given a reward, this method updates the h matrix.

        Parameters
        ----------
        reward : float
            Value of the obtained reward.
        """
        if len(self.initial_prob_distr[0]) > 0:
            self.h_matrix =  self.h_matrix - self.gamma_damping * (self.h_matrix - self.h_0) + reward * self.g_matrix
        else:
            self.h_matrix =  self.h_matrix - self.gamma_damping * (self.h_matrix - 1.) + reward * self.g_matrix
            
    def reset_g(self):
        """
        Resets the g_matrix.
        """
        self.g_matrix = np.zeros((self.num_actions, self.num_percepts), dtype=np.float64)
        
    def deliberate_fixed_policy(self, observation):
        """
        Given an observation , this method chooses the next action according to the fixed policy specified as attribute of the class.

        Parameters
        ----------
        observation : list
            List that describes the observation, as specified in percept_preprocess.

        Returns
        -------
        action : int
            Index of the chosen action.

        """
        percept = self.percept_preprocess(observation) 
        if len(self.fixed_policy[0]) > 0:
            action = rand_choice_nb(arr = np.arange(self.num_actions), prob = self.fixed_policy[percept])
        else:
            print('No fixed policy was given to the agent. The action will be selected randomly.')
            action = np.random.choice(self.num_actions)
    
        self.g_matrix = (1 - self.eta_glow_damping) * self.g_matrix
        self.g_matrix[action, percept] += 1 #record latest decision in g_matrix
    
        return action
    
    def act(self, action):
        """
        Agent performs the given action.

        Parameters
        ----------
        action : int (0, 1)
            1 if it changes direction, 0 otherwise
        """
        
        # If the agent changes direction   
        if action == 1:
            self.agent_state = 0
        else:
            self.agent_state += 1  
            
    
    def get_state(self):  
        ''' simplified to case of single forager. Returns list because is what deliberate needs'''
        return np.array([self.agent_state])

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #ebf9d445
@jitclass([("agent_states", int64[:]), 
           ("size_state_space", int64[:]),  
           ("h_matrix", float64[:,:,:]) ,
           ("g_matrix", float64[:,:,:]) ,
           ("h_0", float64[:,:,:]),
          ])
class Foragers():
    num_agents : int
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_states: np.ndarray
    size_state_space: np.ndarray
    initial_h_0: bool
    h_matrix: np.ndarray
    g_matrix: np.ndarray
    h_0: np.ndarray
    g_update : str
    
    def __init__(self, 
                 # Number of agents,
                 num_agents : int,
                 # Number of actions the agent can take
                 num_actions : int, 
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature 
                 size_state_space : np.ndarray, 
                 # Gamma damping from PS
                 gamma_damping=0.0, 
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard', 
                 # Beta parameter for softmax policy
                 beta_softmax=3, 
                 # If to consider initial probability distribution for the H matrix or not. 
                 initial_h_0 = False,
                 # value of initial h_matrix
                 h_0 = np.array([[[],[],[]]]),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 # Works as follows: s (sum) -> g_mat += 1 or r (reset) -> gmat = 1 when updating gmat
                 g_update = 's', 
                ):
        """

        This class defines a Foragers agent, an extension of the Forager class to multi agent scenarios efficiently.
        """
        self.num_agents = num_agents

        self.agent_states = np.zeros(num_agents, dtype=np.int64)
        
        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space)) # total number of possible percepts
        
        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.g_update = g_update
      
        self.initial_h_0 = initial_h_0
        self.h_0 = h_0
        
        self.init_matrices()        

    def reset_g(self):
        """
        Resets the g_matrix.
        """
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)                          
        
    def init_matrices(self):

        self.reset_g()

        # initialize h matrix with different values
        if self.initial_h_0: 
            self.h_matrix = self.h_0.copy()
        else: 
            self.h_matrix = np.ones((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64) #Note: the first index specifies the action, the second index specifies the percept.
            
    def learn(self, rewards):
        """
        Given rewards, this method updates the h matrix.

        Parameters
        ----------
        rewards : array of floats, shape (num_agents,)
            Values of the obtained rewards for each agent.
        """
        if self.initial_h_0: 
            self.h_matrix = self.h_matrix - self.gamma_damping * (self.h_matrix - self.h_0) + rewards[:, None, None] * self.g_matrix
        else:
            self.h_matrix = self.h_matrix - self.gamma_damping * (self.h_matrix - 1.) + rewards[:, None, None] * self.g_matrix      
            
    def percept_preprocess(self, observations):
        """
        Takes a multi-feature percept and reduces it to a single integer index.

        Parameters
        ----------
        observations : array of FLOAT&$ (!!!) >=0, of the same length as self.num_percepts_list
            List that describes the observation. Each entry is the value that each feature takes in the observation.
            observation[i] < num_percepts_list[i] (strictly)

        Returns
        -------
        percept : int
            Percept index that corresponds to the input observation.

        """

        # Compute the cumulative product of the state space dimensions
        state_space_factors = np.zeros(len(self.size_state_space))
        state_space_factors[0] = 1
        state_space_factors[1:] = np.cumprod(self.size_state_space[:-1])

        # Use matrix multiplication to compute percepts for all agents
        percepts = np.dot(observations, state_space_factors)

        return percepts.astype(np.int64)  # Ensure the output is of integer type
    
    def deliberate(self, observations):
        """
        Given an observation , this method chooses the next action and records that choice in the g_matrix.

        Parameters
        ----------
        observations : array of observations, shape (num_agents, num_features)
        action : optional, bool
            Mostly for debugging, we can input the action and no deliberation takes place, but g_matrix is updated

        Returns
        -------
        actions : array
            Containing the action of each agent.

        """
        percepts = self.percept_preprocess(observations) 

        probs = self.probability_distr(percepts)
     
        actions = rand_choice_vectorized(probs = probs)  

        self.g_matrix = (1 - self.eta_glow_damping) * self.g_matrix
        # Loop-based approach to update g_matrix
        for i in range(self.num_agents):
            self.g_matrix[i, actions[i], percepts[i]] += 1  # Update the corresponding element
        
        return actions
    
    def probability_distr(self, percepts):
        """
         
        Given a percept index, this method returns a probability distribution over actions.

        Parameters
        ----------
        percepts : array of ints
            Indices of the given percepts.

        Returns
        -------
        probability_distr : np.array, length = num_actions
            Probability for each action (normalized to unit sum), computed according to policy_type.

        """

        # No Numba version of standard (for reference):
        # # Extract h_matrix for all agents and the given percept
        # h_vectors = self.h_matrix[np.arange(self.num_agents), :, percepts] 
        # # Compute probability distribution for all agents
        # probability_distr = h_vectors / np.sum(h_vectors, axis=1, keepdims=True)  

        # Preallocate the result array
        probability_distr = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            # Loop over agents to extract h_vectors and compute probabilities
            for i in range(self.num_agents):
                h_vector = self.h_matrix[i, :, percepts[i]]
                probability_distr[i, :] = h_vector / np.sum(h_vector)

        elif self.policy_type == 'softmax':
            # Loop over agents to extract h_vectors and compute softmax probabilities
            for i in range(self.num_agents):
                h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                h_vector_mod = h_vector - np.max(h_vector)  # Stabilize softmax
                probability_distr[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        return probability_distr       
    
       
    
    def act(self, actions):
        """
        Agent performs the given actions.

        Parameters
        ----------
        actions : array of ints (0, 1)
            1 if it changes direction, 0 otherwise
        """
        
        # If the agent changes direction   
        self.agent_states[actions == 1] = 0
        self.agent_states[actions == 0] += 1
            
    
    def get_state(self):  
        ''' Returns the counter of all agents in the form of arra'''
        return self.agent_states

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #613a24f0
@jitclass([("agent_states", int64[:]),
           ("size_state_space", int64[:]),
           ("h_matrix", float64[:,:,:]),
           ("g_matrix", float64[:,:,:]),
           ("h_0", float64[:,:,:]),
           ("prefactor_1", float64[:]),
           ("prefactor_2", float64[:]),
           ("last_upd_G", float64[:,:,:]),
           ("N_upd_H", int64[:]),
           ("N_upd_G", int64[:]),
           ("state_space_factors", float64[:])
          ])
class Foragers_efficient():
    num_agents : int
    num_actions : int
    gamma_damping : float
    eta_glow_damping : float
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_states: np.ndarray
    size_state_space: np.ndarray
    initial_h_0: bool
    h_matrix: np.ndarray
    g_matrix: np.ndarray
    h_0: np.ndarray
    g_update : str
    state_space_factors : np.ndarray
    # Efficient H update
    prefactor_1: np.ndarray
    prefactor_2: np.ndarray
    max_no_H_update : int
    N_upd_H : np.ndarray
    # Efficient G update
    last_upd_G: np.ndarray
    N_upd_G: np.ndarray

    def __init__(self,
                 # Number of agents
                 num_agents : int,
                 # Number of actions the agent can take
                 num_actions : int,
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature
                 size_state_space : np.ndarray,
                 # Gamma damping from PS
                 gamma_damping=0.0,
                 # Eta damping from PS
                 eta_glow_damping=0.0,
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard',
                 # Beta parameter for softmax policy
                 beta_softmax=3,
                 # If to consider initial probability distribution for the H matrix or not.
                 initial_h_0=False,
                 # value of initial h_matrix
                 h_0=np.array([[[],[],[]]]),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 g_update='s',
                 # Max number of steps without updating the H matrix
                 max_no_H_update=int(1e4),
                ):
        """
        Efficient version of Foragers. Uses lazy H-matrix and G-matrix updates
        (only on reward or when max_no_H_update is reached), following the same
        strategy as the single-agent Forager class.

        Key differences vs Foragers:
          - H-matrix is NOT updated every step. Instead, prefactors are used to
            compute the virtually-updated H column on the fly in deliberate().
          - G-matrix updates are lazy: only the (agent, action, percept) entry
            touched during deliberate() is updated; the rest are deferred.
          - _learn_post_reward(rewards) replaces learn(rewards). It flushes the
            pending G-matrix decays and applies the accumulated H-matrix damping
            for each agent that received a reward (or hit max_no_H_update).
        """
        self.num_agents = num_agents
        self.agent_states = np.zeros(num_agents, dtype=np.int64)

        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space))

        # precompute factors for percept_preprocess
        self.state_space_factors = np.zeros(len(self.size_state_space), dtype=np.float64)
        self.state_space_factors[0] = 1
        self.state_space_factors[1:] = np.ascontiguousarray(np.cumprod(self.size_state_space[:-1]))

        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping
        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.g_update = g_update

        self.initial_h_0 = initial_h_0
        self.h_0 = h_0

        self.init_matrices()

        # Efficient H update prefactors (same as Forager)
        self.max_no_H_update = max_no_H_update
        self.N_upd_H = np.zeros(num_agents, dtype=np.int64)
        self.prefactor_1 = (1 - self.gamma_damping) ** np.arange(1, self.max_no_H_update + 1)
        self.prefactor_2 = np.zeros(self.max_no_H_update)
        for i in range(max_no_H_update):
            self.prefactor_2[i] = self.gamma_damping * np.sum(
                (1 - self.gamma_damping) ** np.arange(i + 1)
            )

        # Efficient G update tracking (per-agent)
        self.N_upd_G = np.zeros(num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((num_agents, self.num_actions, self.num_percepts))

    def init_matrices(self):
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        if self.initial_h_0:
            self.h_matrix = self.h_0.copy()
        else:
            self.h_matrix = np.ones((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)

    def reset_g(self):
        """Resets g_matrix and all update counters (H and G)."""
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        self.N_upd_H = np.zeros(self.num_agents, dtype=np.int64)
        self.N_upd_G = np.zeros(self.num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((self.num_agents, self.num_actions, self.num_percepts))

    def increment_counters(self):
        """Increment N_upd_H and N_upd_G for all agents. Call at start of each timestep."""
        for i in range(self.num_agents):
            self.N_upd_H[i] += 1
            self.N_upd_G[i] += 1

    # ── Efficient G-matrix updates ────────────────────────────────────────

    def _G_upd_single_percept(self, agent_idx, percept, action):
        """Lazily update G for a single (agent, action, percept) tuple."""
        if self.g_update == 's':
            decay = (1 - self.eta_glow_damping) ** (
                self.N_upd_G[agent_idx] - self.last_upd_G[agent_idx, action, percept]
            )
            self.g_matrix[agent_idx, action, percept] = (
                decay * self.g_matrix[agent_idx, action, percept] + 1
            )
        elif self.g_update == 'r':
            self.g_matrix[agent_idx, action, percept] = 1
        self.last_upd_G[agent_idx, action, percept] = self.N_upd_G[agent_idx]

    def _G_upd_full(self, agent_idx):
        """Apply all pending G-matrix decays for one agent, then reset its counters."""
        n = self.N_upd_G[agent_idx]
        for a in range(self.num_actions):
            for p in range(self.num_percepts):
                self.g_matrix[agent_idx, a, p] *= (
                    (1 - self.eta_glow_damping) ** (n - self.last_upd_G[agent_idx, a, p])
                )
                self.last_upd_G[agent_idx, a, p] = 0.0
        self.N_upd_G[agent_idx] = 0

    # ── Efficient H-matrix updates ────────────────────────────────────────

    def _H_upd_single_percept(self, agent_idx, t, percept):
        """Return the virtually-updated h_matrix column for one agent/percept
        without modifying h_matrix."""
        if self.initial_h_0:
            return (self.prefactor_1[t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[t - 1] * self.h_0[agent_idx, :, percept])
        else:
            return (self.prefactor_1[t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[t - 1])

    def _learn_post_reward(self, rewards):
        """Update H (and flush G) for each agent that received a reward or hit max_no_H_update.
        
        Parameters
        ----------
        rewards : array of floats, shape (num_agents,)
        """
        for i in range(self.num_agents):
            if rewards[i] > 0 or self.N_upd_H[i] >= self.max_no_H_update - 1:
                if self.N_upd_H[i] == 0:
                    continue
                self._G_upd_full(i)
                if self.initial_h_0:
                    self.h_matrix[i] = (
                        self.prefactor_1[self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[self.N_upd_H[i] - 1] * self.h_0[i]
                        + rewards[i] * self.g_matrix[i]
                    )
                else:
                    self.h_matrix[i] = (
                        self.prefactor_1[self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[self.N_upd_H[i] - 1]
                        + rewards[i] * self.g_matrix[i]
                    )
                self.N_upd_H[i] = 0

    # ── Percept preprocessing ─────────────────────────────────────────────

    def percept_preprocess(self, observations):
        """Same as Foragers.percept_preprocess."""
        
        percepts = np.dot(observations, np.ascontiguousarray(self.state_space_factors))
        return percepts.astype(np.int64)

    # ── Deliberation ──────────────────────────────────────────────────────

    def deliberate(self, observations):
        """
        Like Foragers.deliberate but uses efficient H lookup and lazy G update.
        """
        percepts = self.percept_preprocess(observations)

        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        actions = rand_choice_vectorized(probs=probs)

        for i in range(self.num_agents):
            self._G_upd_single_percept(i, percepts[i], actions[i])

        return actions

    def probability_distr(self, percepts):
        """Like Foragers.probability_distr but uses efficient H lookup."""
        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        return probs

    # ── Action & state ────────────────────────────────────────────────────

    def act(self, actions):
        """Same as Foragers.act."""
        self.agent_states[actions == 1] = 0
        self.agent_states[actions == 0] += 1

    def get_state(self):
        """Same as Foragers.get_state."""
        return self.agent_states

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #9c8d9a8b
@jitclass([("agent_states", int64[:]),
           ("size_state_space", int64[:]),
           ("h_matrix", float64[:,:,:]),
           ("g_matrix", float64[:,:,:]),
           ("h_0", float64[:,:,:]),
           ("gamma_damping", float64[:]),
           ("eta_glow_damping", float64[:]),
           ("is_learning", boolean[:]),
           ("prefactor_1", float64[:,:]),
           ("prefactor_2", float64[:,:]),
           ("last_upd_G", float64[:,:,:]),
           ("N_upd_H", int64[:]),
           ("N_upd_G", int64[:]),
           ("state_space_factors", float64[:])
          ])
class Foragers_efficient_ind():
    num_agents : int
    num_actions : int
    gamma_damping : np.ndarray
    eta_glow_damping : np.ndarray
    is_learning : np.ndarray
    policy_type : str
    beta_softmax : float
    num_percepts : int
    agent_states: np.ndarray
    size_state_space: np.ndarray
    initial_h_0: bool
    h_matrix: np.ndarray
    g_matrix: np.ndarray
    h_0: np.ndarray
    g_update : str
    state_space_factors : np.ndarray
    # Efficient H update
    prefactor_1: np.ndarray
    prefactor_2: np.ndarray
    max_no_H_update : int
    N_upd_H : np.ndarray
    # Efficient G update
    last_upd_G: np.ndarray
    N_upd_G: np.ndarray

    def __init__(self,
                 # Number of agents
                 num_agents : int,
                 # Number of actions the agent can take
                 num_actions : int,
                 # Size of the state space, given as an array where each entry is the dimension of each environmental feature
                 size_state_space : np.ndarray,
                 # Per-agent gamma damping from PS, length = num_agents
                 gamma_damping=np.array([0.0]),
                 # Per-agent eta damping from PS, length = num_agents
                 eta_glow_damping=np.array([0.0]),
                 # Per-agent learning flag. True -> train this agent, False -> freeze h_matrix.
                 is_learning=np.array([True]),
                 # Policy type. Can be 'standard' or 'softmax'
                 policy_type='standard',
                 # Beta parameter for softmax policy
                 beta_softmax=3,
                 # If to consider initial probability distribution for the H matrix or not.
                 initial_h_0=False,
                 # value of initial h_matrix
                 h_0=np.array([[[],[],[]]]),
                 # Type of update for the G matrix. Can be 's' (sum) or 'r' (reset)
                 g_update='s',
                 # Max number of steps without updating the H matrix
                 max_no_H_update=int(1e4),
                ):
        """
        Per-agent damping version of Foragers_efficient.

        gamma_damping and eta_glow_damping are arrays of shape (num_agents,),
        so each agent can use independent damping values.

        is_learning is a boolean array of shape (num_agents,), controlling whether
        each agent updates h_matrix (True) or remains frozen (False).
        """
        self.num_agents = num_agents
        self.agent_states = np.zeros(num_agents, dtype=np.int64)

        self.num_actions = num_actions
        self.size_state_space = size_state_space
        self.num_percepts = int(np.prod(self.size_state_space))

        # precompute factors for percept_preprocess
        self.state_space_factors = np.zeros(len(self.size_state_space), dtype=np.float64)
        self.state_space_factors[0] = 1
        self.state_space_factors[1:] = np.ascontiguousarray(np.cumprod(self.size_state_space[:-1]))

        self.gamma_damping = gamma_damping
        self.eta_glow_damping = eta_glow_damping

        if len(is_learning) == 1:
            self.is_learning = np.full(num_agents, is_learning[0], dtype=np.bool_)
        else:
            self.is_learning = is_learning

        self.policy_type = policy_type
        self.beta_softmax = beta_softmax
        self.g_update = g_update

        self.initial_h_0 = initial_h_0
        self.h_0 = h_0

        self.init_matrices()

        # Efficient H update prefactors (per agent)
        self.max_no_H_update = max_no_H_update
        self.N_upd_H = np.zeros(num_agents, dtype=np.int64)
        self.prefactor_1 = np.zeros((num_agents, self.max_no_H_update), dtype=np.float64)
        self.prefactor_2 = np.zeros((num_agents, self.max_no_H_update), dtype=np.float64)

        for ag in range(num_agents):
            g = self.gamma_damping[ag]
            self.prefactor_1[ag] = (1 - g) ** np.arange(1, self.max_no_H_update + 1)
            for i in range(max_no_H_update):
                self.prefactor_2[ag, i] = g * np.sum((1 - g) ** np.arange(i + 1))

        # Efficient G update tracking (per-agent)
        self.N_upd_G = np.zeros(num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((num_agents, self.num_actions, self.num_percepts))

    def init_matrices(self):
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        if self.initial_h_0:
            self.h_matrix = self.h_0.copy()
        else:
            self.h_matrix = np.ones((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)

    def reset_g(self):
        """Resets g_matrix and all update counters (H and G)."""
        self.g_matrix = np.zeros((self.num_agents, self.num_actions, self.num_percepts), dtype=np.float64)
        self.N_upd_H = np.zeros(self.num_agents, dtype=np.int64)
        self.N_upd_G = np.zeros(self.num_agents, dtype=np.int64)
        self.last_upd_G = np.zeros((self.num_agents, self.num_actions, self.num_percepts))

    def increment_counters(self):
        """Increment N_upd_H and N_upd_G only for trainable agents."""
        for i in range(self.num_agents):
            if self.is_learning[i]:
                self.N_upd_H[i] += 1
                self.N_upd_G[i] += 1

    # Efficient G-matrix updates

    def _G_upd_single_percept(self, agent_idx, percept, action):
        """Lazily update G for a single (agent, action, percept) tuple."""
        if not self.is_learning[agent_idx]:
            return

        if self.g_update == 's':
            decay = (1 - self.eta_glow_damping[agent_idx]) ** (
                self.N_upd_G[agent_idx] - self.last_upd_G[agent_idx, action, percept]
            )
            self.g_matrix[agent_idx, action, percept] = (
                decay * self.g_matrix[agent_idx, action, percept] + 1
            )
        elif self.g_update == 'r':
            self.g_matrix[agent_idx, action, percept] = 1
        self.last_upd_G[agent_idx, action, percept] = self.N_upd_G[agent_idx]

    def _G_upd_full(self, agent_idx):
        """Apply all pending G-matrix decays for one agent, then reset its counters."""
        n = self.N_upd_G[agent_idx]
        for a in range(self.num_actions):
            for p in range(self.num_percepts):
                self.g_matrix[agent_idx, a, p] *= (
                    (1 - self.eta_glow_damping[agent_idx]) ** (n - self.last_upd_G[agent_idx, a, p])
                )
                self.last_upd_G[agent_idx, a, p] = 0.0
        self.N_upd_G[agent_idx] = 0

    # Efficient H-matrix updates

    def _H_upd_single_percept(self, agent_idx, t, percept):
        """Return the virtually-updated h_matrix column for one agent/percept
        without modifying h_matrix."""
        if self.initial_h_0:
            return (self.prefactor_1[agent_idx, t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[agent_idx, t - 1] * self.h_0[agent_idx, :, percept])
        else:
            return (self.prefactor_1[agent_idx, t - 1] * self.h_matrix[agent_idx, :, percept]
                    + self.prefactor_2[agent_idx, t - 1])

    def _learn_post_reward(self, rewards):
        """Update H (and flush G) for each trainable agent that received a reward or hit max_no_H_update.

        Parameters
        ----------
        rewards : array of floats, shape (num_agents,)
        """
        for i in range(self.num_agents):
            if not self.is_learning[i]:
                self.N_upd_H[i] = 0
                self.N_upd_G[i] = 0
                continue

            if rewards[i] > 0 or self.N_upd_H[i] >= self.max_no_H_update - 1:
                if self.N_upd_H[i] == 0:
                    continue
                self._G_upd_full(i)
                if self.initial_h_0:
                    self.h_matrix[i] = (
                        self.prefactor_1[i, self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[i, self.N_upd_H[i] - 1] * self.h_0[i]
                        + rewards[i] * self.g_matrix[i]
                    )
                else:
                    self.h_matrix[i] = (
                        self.prefactor_1[i, self.N_upd_H[i] - 1] * self.h_matrix[i]
                        + self.prefactor_2[i, self.N_upd_H[i] - 1]
                        + rewards[i] * self.g_matrix[i]
                    )
                self.N_upd_H[i] = 0

    # Percept preprocessing

    def percept_preprocess(self, observations):
        """Same as Foragers.percept_preprocess."""
        percepts = np.dot(observations, np.ascontiguousarray(self.state_space_factors))
        return percepts.astype(np.int64)

    # Deliberation

    def deliberate(self, observations):
        """
        Like Foragers.deliberate but uses efficient H lookup and lazy G update.
        """
        percepts = self.percept_preprocess(observations)

        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        actions = rand_choice_vectorized(probs=probs)

        for i in range(self.num_agents):
            self._G_upd_single_percept(i, percepts[i], actions[i])

        return actions

    def probability_distr(self, percepts):
        """Like Foragers.probability_distr but uses efficient H lookup."""
        probs = np.zeros((self.num_agents, self.num_actions), dtype=np.float64)

        if self.policy_type == 'standard':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self._H_upd_single_percept(i, self.N_upd_H[i], percepts[i])
                probs[i, :] = h_vector / np.sum(h_vector)
        elif self.policy_type == 'softmax':
            for i in range(self.num_agents):
                if self.N_upd_H[i] == 0:
                    h_vector = self.beta_softmax * self.h_matrix[i, :, percepts[i]]
                else:
                    h_vector = self.beta_softmax * self._H_upd_single_percept(
                        i, self.N_upd_H[i], percepts[i]
                    )
                h_vector_mod = h_vector - np.max(h_vector)
                probs[i, :] = np.exp(h_vector_mod) / np.sum(np.exp(h_vector_mod))

        return probs

    # Action & state

    def act(self, actions):
        """Same as Foragers.act."""
        self.agent_states[actions == 1] = 0
        self.agent_states[actions == 0] += 1

    def get_state(self):
        """Same as Foragers.get_state."""
        return self.agent_states

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #dbfcbdf9
@njit
def train_loop_reset(episodes, time_ep, agent, env, h_mat_allT = False, when_save_h_mat = 1, reset_after_reward = True):  

    if h_mat_allT: 
        policy_t = np.zeros((int(np.ceil(episodes/when_save_h_mat)), 
                             agent.h_matrix.shape[-1]))
        idx_policy_save = 0
        
    save_rewards = np.zeros(episodes)
    
    for ep in range(episodes):
        
        #initialize environment and agent's counter and g matrix
        env.init_env()
        agent.agent_state = 0
        agent.reset_g()

        for t in range(time_ep):
            agent.N_upd_H += 1
            agent.N_upd_G += 1

            #get perception
            state = agent.get_state()
            
            # if we reached the maximum state space, we perform turn action
            if state == agent.h_matrix.shape[-1]:
                action = 1
            # else we do as normal    
            else: 
                action = agent.deliberate(state)
                
            #act (update counter)
            agent.act(action)

            #update positions
            reward = env.update_pos(action)            

            if reward == 1 or agent.N_upd_H == agent.max_no_H_update-1:
                agent._learn_post_reward(reward)
            
            if reset_after_reward == True and reward != 0:
                agent.agent_state = 0

            # Saving
            save_rewards[ep] += reward
        if h_mat_allT and ep % when_save_h_mat == 0:
            policy_t[idx_policy_save] = agent.h_matrix[0,:] / agent.h_matrix.sum(0)
            idx_policy_save += 1
      
    return (save_rewards/time_ep, policy_t) if h_mat_allT else (save_rewards/time_ep, agent.h_matrix)

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #6a1927d1
from .environments import ResetEnv_1D



@njit(parallel = True)
def run_agents_reset_1D(episodes, time_ep, N_agents,
                       # Environment props
                       D = 1/2, L = 10.0, 
                       # Agent props
                       num_actions = 2,
                       size_state_space = np.array([100]),
                       gamma_damping = 0.00001,
                       eta_glow_damping = 0.1,
                       g_update = 's',
                       initial_prob_distr = np.array([[],[]]),
                       policy_type = 'standard', 
                       beta_softmax = 3,  
                       fixed_policy = np.array([[],[]]),
                       max_no_H_update = int(1e3),
                       h_mat_allT = False, 
                       reset_after_reward = True,
                       # When we want N_agent != number of max cores, we use this to make few runs
                       # over the selected number of cores, given by N_agents.
                       num_runs = None 
                      ):

    if num_runs is None:
        total_agents = N_agents
    else:
        total_agents = N_agents*num_runs
    
    save_rewards = np.zeros((total_agents, episodes))
    if h_mat_allT:
        save_h_matrix = np.zeros((total_agents, episodes, size_state_space.prod()))  
    else:        
        save_h_matrix = np.zeros((total_agents, 2, size_state_space.prod())) 

    # if N_agents is an integer, we consider that we run this at full cores
    if num_runs is None:
    
        for n_agent in prange(N_agents):
            
            agent = Forager(num_actions, size_state_space,
                                      gamma_damping, eta_glow_damping, 
                                      policy_type, beta_softmax,
                                      initial_prob_distr,fixed_policy,max_no_H_update,g_update)
            env = ResetEnv_1D(L, D)
            
            rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
     
            # print(rews.shape, rews[0], rews[0].dtype)
            
            save_rewards[n_agent] = rews
            save_h_matrix[n_agent] = mat

    # If it is a list, the first number is the number of parallel agents and the second the 
    # times we run those parallel agents
    else:

        n_run = -1        
        for run in range(num_runs):
            n_run += 1
            for idxa in prange(N_agents):
            
                agent = Forager(num_actions, size_state_space,
                                gamma_damping, eta_glow_damping, 
                                policy_type, beta_softmax,
                                initial_prob_distr,fixed_policy,max_no_H_update, g_update)
                env = ResetEnv_1D(L, D)
                
                rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
                         
                save_rewards[idxa*num_runs+n_run] = rews
                save_h_matrix[idxa*num_runs+n_run] = mat
        
        
    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #53149e60
from .environments import ResetEnv_2D


@njit(parallel = True)
def run_agents_reset_2D(episodes, time_ep, N_agents,
                     # Environment props
                     dist_target = 10.0, radius_target = 1.0, D = 1/2,
                     # Agent props
                     num_actions = 2,
                     size_state_space = np.array([100]),
                     gamma_damping = 0.00001,
                     eta_glow_damping = 0.1,
                     initial_prob_distr = np.array([[],[]]),
                     policy_type = 'standard', 
                     beta_softmax = 3,  
                     fixed_policy = np.array([[],[]]),
                     max_no_H_update = int(1e3),
                     h_mat_allT = False, when_save_h_mat = 1,
                     reset_after_reward = True,
                     g_update = 's',
                    # When we want N_agent != number of max cores, we use this to make few runs
                    # over the selected number of cores, given by N_agents.
                    num_runs = None                         
                      ):
    
    save_rewards = np.zeros((N_agents, episodes))
    if h_mat_allT:
        save_h_matrix = np.zeros((N_agents, 
                                  int(np.ceil(episodes/when_save_h_mat)), 
                                  size_state_space.prod()))  
    else:        
        save_h_matrix = np.zeros((N_agents, 2, size_state_space.prod())) 

    # if N_agents is an integer, we consider that we run this at full cores
    if num_runs is None:
    
        for n_agent in prange(N_agents):
            
            agent = Forager(num_actions, size_state_space,
                            gamma_damping, eta_glow_damping, 
                            policy_type, beta_softmax,
                            initial_prob_distr,fixed_policy,max_no_H_update,g_update)
            
            env = ResetEnv_2D(dist_target, radius_target, D)
            
            rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, when_save_h_mat, reset_after_reward)            
    
        
            save_rewards[n_agent] = rews
            save_h_matrix[n_agent] = mat

    # If it is a list, the first number is the number of parallel agents and the second the 
    # times we run those parallel agents
    else:

        n_run = -1        
        for run in range(num_runs):
            n_run += 1
            for idxa in prange(N_agents):
            
                agent = Forager(num_actions, size_state_space,
                                gamma_damping, eta_glow_damping, 
                                policy_type, beta_softmax,
                                initial_prob_distr,fixed_policy,max_no_H_update, g_update)
                env = ResetEnv_2D(dist_target, radius_target, D)
                
                rews, mat = train_loop_reset(episodes, time_ep, agent, env, h_mat_allT, reset_after_reward)            
                         
                save_rewards[idxa*num_runs+n_run] = rews
                save_h_matrix[idxa*num_runs+n_run] = mat
        
    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #441c899b
@njit
def train_loop_collective(episodes, time_ep, env, agents, max_counter, visual_activated = False, upd_pos_method = 'RND', ablation = None,
             no_learning = False):
    """
    Training loop for multiple agents in a 2D environment with collective behavior.

    Parameters
    ----------
    episodes : int
        Number of episodes to run.
    time_ep : int
        Number of time steps per episode.
    env : ResetEnv_2D
        The environment in which the agents operate.
    agents : Foragers_efficient
        The agents that will interact with the environment.
    max_counter : int
        The maximum value for the agents' counters.
    visual_activated : bool, optional
        Whether visual perception is activated for the agents. Default is False.
    upd_pos_method : str, optional
        The method for updating agent positions ('RND' or 'LR'). Default is 'RND'.
    ablation : str, optional
        If 'non_r', the non-rewarded agent state is always kept at 0. If 'r', the rewarded agent state is always kept at 0. Default is None.
    no_learning : bool, optional
        If True, agents will not learn from rewards. Default is False.

    """
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()
        
        # Debugging
        # positions = np.zeros((time_ep, env.num_agents, 2))

        for t in range(time_ep):
            agents.increment_counters()

            # --- Build observations ---
            # 1) Counter (clipped)
            counters = np.minimum(agents.get_state().copy(), np.int64(max_counter - 1))

            # 2) Cone features
            if visual_activated:
                _, agents_spot = env.agents_in_cone()
                # agents_spot is (num_agents, num_agents) with 1 if j is in i's cone

            # any_agent_in_cone: 1 if row sum > 0
            any_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated and ablation != 'non_r':
                for i in range(agents.num_agents):
                    if agents_spot[i].sum() > 0:
                        any_in_cone[i] = 1.0

            # rewarded_agent_in_cone: 1 if any agent with rewarded_agents==1 is in cone
            rewarded_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated and ablation != 'r':
                for i in range(agents.num_agents):
                    for j in range(agents.num_agents):
                        if agents_spot[i, j] == 1 and env.rewarded_agents[j] == 1:
                            rewarded_in_cone[i] = 1.0
                            break

            # observations shape: (num_agents, 3)
            observations = np.empty((agents.num_agents, 3), dtype=np.float64)
            observations[:, 0] = counters.astype(np.float64)
            observations[:, 1] = any_in_cone
            observations[:, 2] = rewarded_in_cone

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset counter BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step
            if upd_pos_method == 'RND':
                env.update_pos(actions == 1)
            elif upd_pos_method == 'LR':
                env.update_pos(actions)                
            env.check_bc()
            env.update_target_state()
            env.update_rewarded_agents()

            rewards = env.check_encounter()
            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            if not no_learning:
                agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1
        
        # Debugging
        #     positions[t] = env.positions
        # for p in positions.transpose(1, 0, 2):
        #     plt.plot(p[:, 0], p[:, 1], '-')
        # plt.show()

    return save_rewards, agents.h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #0965b580
from .environments import CollectiveEnv

@njit(parallel=True)
def run_collective(episodes, time_ep, runs,
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated = True,
             # Agent props
             num_actions=2,
             state_space=np.array([50, 2, 2]),
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method = 'RND', # Method to update position. 'RND' for random angle turns, 'LR' for left/right turns.
             turn_angle = np.pi/4, # Angle for left/right turns if upd_pos_method is 'LR'.
             ablation = None,
             no_learning = False
             ):
    """
    Parallel launcher for collective training, where visual features are 
    if yes/no seeing an agent in front and if yes/no seeing a rewarded agent in front:
    
    state_space = np.array([max_counter, 2, 2])
    """
    save_h_matrix = np.zeros((runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((runs, num_agents, episodes))

    for n_run in prange(runs):
        agents = Foragers_efficient(
            num_agents, num_actions, state_space,
            gamma_damping, eta_glow_damping, policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )
        env = CollectiveEnv(num_agents, Nt, L, r, tau, agent_step,
                            visual_range, visual_angle, shared_depletion, tau_reward, upd_pos_method, turn_angle)

        rews, mat = train_loop_collective(episodes, time_ep, env, agents, state_space[0], visual_activated, upd_pos_method, ablation, no_learning)

        for t in range(episodes):
            save_rewards[n_run, :, t] = rews[:, t]
        save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #827ec705
from .environments import CollectiveEnv

@njit(parallel=True)
def run_collective_dict(episodes, time_ep,
             # Environment props — pass as 1-D arrays; use length-1 arrays for fixed values.
             # At most 2 of the array-valued parameters should have length > 1 (parameter sweep).
             Nt=np.array([100]),
             L=np.array([100.0]),
             r=np.array([0.5]),
             tau=np.array([5]),
             tau_reward=np.array([1]),
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated=True,
             # Agent props
             num_actions=2,
             state_space=np.array([50, 2, 2]),
             gamma_damping=np.array([0.00001]),
             eta_glow_damping=np.array([0.1]),
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method='RND',
             turn_angle=np.array([np.pi / 4]),
             n_run=1,
             ablation = None
             ):
    """
    Parallel launcher for collective training sweeping over parameter combinations.

    Up to 2 of the array-valued parameters (Nt, L, r, tau, tau_reward,
    gamma_damping, eta_glow_damping, turn_angle) may have length > 1; prange
    iterates over all Cartesian-product combinations.  Fixed parameters should
    be passed as length-1 arrays (e.g. np.array([0.5]) for r).

    n_run controls how many independent repetitions are run per parameter combo.
    All repetitions across all combos are executed in parallel via a single prange.

    state_space = np.array([max_counter, 2, 2])

    Returns
    -------
    save_rewards  : (n_run, total_combos, num_agents, episodes)
    save_h_matrix : (n_run, total_combos, num_agents, num_actions, state_space.prod())

    The flat combo index follows the ordering:
        combo = i_Nt + n_Nt*(i_L + n_L*(i_r + n_r*(i_tau + n_tau*(
                  i_tau_reward + n_tau_reward*(i_gamma + n_gamma*(
                    i_eta + n_eta*i_turn))))))
    """
    n_Nt         = len(Nt)
    n_L          = len(L)
    n_r          = len(r)
    n_tau        = len(tau)
    n_tau_reward = len(tau_reward)
    n_gamma      = len(gamma_damping)
    n_eta        = len(eta_glow_damping)
    n_turn       = len(turn_angle)
    n_VR         = len(visual_range)

    total_combos = n_Nt * n_L * n_r * n_tau * n_tau_reward * n_gamma * n_eta * n_turn * n_VR
    total_iters  = total_combos * n_run

    save_h_matrix = np.zeros((n_run, total_combos, num_agents, num_actions, state_space.prod()))
    save_rewards  = np.zeros((n_run, total_combos, num_agents, episodes))

    # Precompute cumulative strides for combo index decomposition
    stride_L    = n_Nt
    stride_r    = stride_L    * n_L
    stride_tau  = stride_r    * n_r
    stride_tr   = stride_tau  * n_tau
    stride_gam  = stride_tr   * n_tau_reward
    stride_eta  = stride_gam  * n_gamma
    stride_turn = stride_eta  * n_eta
    stride_VR   = stride_turn * n_turn

    for flat_idx in prange(total_iters):
        run_idx   = flat_idx // total_combos
        combo_idx = flat_idx  % total_combos

        i_Nt         =  combo_idx                % n_Nt
        i_L          = (combo_idx // stride_L)   % n_L
        i_r          = (combo_idx // stride_r)   % n_r
        i_tau        = (combo_idx // stride_tau)  % n_tau
        i_tau_reward = (combo_idx // stride_tr)  % n_tau_reward
        i_gamma      = (combo_idx // stride_gam) % n_gamma
        i_eta        = (combo_idx // stride_eta) % n_eta
        i_turn       = (combo_idx // stride_turn) % n_turn
        i_VR         = (combo_idx // stride_VR) % n_VR

        agents = Foragers_efficient(
            num_agents, num_actions, state_space,
            gamma_damping[i_gamma], eta_glow_damping[i_eta], policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )
        env = CollectiveEnv(num_agents, Nt[i_Nt], L[i_L], r[i_r], tau[i_tau], agent_step,
                            visual_range[i_VR], visual_angle, shared_depletion,
                            tau_reward[i_tau_reward], upd_pos_method, turn_angle[i_turn])

        rews, mat = train_loop_collective(episodes, time_ep, env, agents, state_space[0], visual_activated, upd_pos_method, ablation)

        for t in range(episodes):
            save_rewards[run_idx, combo_idx, :, t] = rews[:, t]
        save_h_matrix[run_idx, combo_idx] = mat

    return save_rewards, save_h_matrix


# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #1cc44678
@njit(parallel=True)
def _run_collect_dict_ind_numba(episodes, time_ep,
                                Nt, L, r, tau, tau_reward,
                                num_agents, agent_step,
                                visual_range, visual_angle,
                                shared_depletion, visual_activated,
                                num_actions, state_space,
                                gamma_damping, eta_glow_damping,
                                is_learning_cases,
                                initial_h_0, h_0, g_update,
                                policy_type, beta_softmax, max_no_H_update,
                                upd_pos_method, turn_angle,
                                n_run, ablation):
    """Numba core for run_collect_dict_ind.

    Expects is_learning_cases as a 2-D bool array with shape (n_cases, num_agents).
    """
    n_Nt = len(Nt)
    n_L = len(L)
    n_r = len(r)
    n_tau = len(tau)
    n_tau_reward = len(tau_reward)
    n_gamma = len(gamma_damping)
    n_eta = len(eta_glow_damping)
    n_turn = len(turn_angle)
    n_VR = len(visual_range)
    n_learn = is_learning_cases.shape[0]

    total_combos = n_Nt * n_L * n_r * n_tau * n_tau_reward * n_gamma * n_eta * n_turn * n_VR * n_learn
    total_iters = total_combos * n_run

    save_h_matrix = np.zeros((n_run, total_combos, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((n_run, total_combos, num_agents, episodes))

    # cumulative strides for combo index decomposition
    stride_L = n_Nt
    stride_r = stride_L * n_L
    stride_tau = stride_r * n_r
    stride_tr = stride_tau * n_tau
    stride_gam = stride_tr * n_tau_reward
    stride_eta = stride_gam * n_gamma
    stride_turn = stride_eta * n_eta
    stride_VR = stride_turn * n_turn
    stride_learn = stride_VR * n_VR

    for flat_idx in prange(total_iters):
        run_idx = flat_idx // total_combos
        combo_idx = flat_idx % total_combos

        i_Nt = (combo_idx // 1) % n_Nt
        i_L = (combo_idx // stride_L) % n_L
        i_r = (combo_idx // stride_r) % n_r
        i_tau = (combo_idx // stride_tau) % n_tau
        i_tau_reward = (combo_idx // stride_tr) % n_tau_reward
        i_gamma = (combo_idx // stride_gam) % n_gamma
        i_eta = (combo_idx // stride_eta) % n_eta
        i_turn = (combo_idx // stride_turn) % n_turn
        i_VR = (combo_idx // stride_VR) % n_VR
        i_learn = (combo_idx // stride_learn) % n_learn

        gamma_vec = np.full(num_agents, gamma_damping[i_gamma])
        eta_vec = np.full(num_agents, eta_glow_damping[i_eta])

        is_learning_case = np.empty(num_agents, dtype=np.bool_)
        for i in range(num_agents):
            is_learning_case[i] = is_learning_cases[i_learn, i]

        agents = Foragers_efficient_ind(
            num_agents, num_actions, state_space,
            gamma_vec, eta_vec, is_learning_case,
            policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )

        env = CollectiveEnv(
            num_agents, Nt[i_Nt], L[i_L], r[i_r], tau[i_tau], agent_step,
            visual_range[i_VR], visual_angle, shared_depletion,
            tau_reward[i_tau_reward], upd_pos_method, turn_angle[i_turn]
        )

        rews, mat = train_loop_collective(
            episodes, time_ep, env, agents, state_space[0],
            visual_activated, upd_pos_method, ablation
        )

        for t in range(episodes):
            save_rewards[run_idx, combo_idx, :, t] = rews[:, t]
        save_h_matrix[run_idx, combo_idx] = mat

    return save_rewards, save_h_matrix


def run_collect_dict_ind(episodes, time_ep,
                         Nt=np.array([100]),
                         L=np.array([100.0]),
                         r=np.array([0.5]),
                         tau=np.array([5]),
                         tau_reward=np.array([1]),
                         num_agents=10,
                         agent_step=1,
                         visual_range=np.array([2.0]),
                         visual_angle=np.pi / 2,
                         shared_depletion=True,
                         visual_activated=True,
                         num_actions=2,
                         state_space=np.array([50, 2, 2]),
                         gamma_damping=np.array([0.00001]),
                         eta_glow_damping=np.array([0.1]),
                         is_learning=np.array([[True]]),
                         initial_h_0=False,
                         h_0=np.zeros((1, 2, 200)),
                         g_update='s',
                         policy_type='standard',
                         beta_softmax=3,
                         max_no_H_update=int(1e3),
                         upd_pos_method='RND',
                         turn_angle=np.array([np.pi / 4]),
                         n_run=1,
                         ablation=None):
    """
    Same parameter sweep as run_collective_dict, with an extra sweep over
    per-agent learning masks for Foragers_efficient_ind.

    is_learning supports:
    - shape (num_agents,) -> treated as a single case
    - shape (n_cases, num_agents) -> one case per row
    - list/list-of-lists equivalents of the above
    """
    Nt = np.asarray(Nt)
    L = np.asarray(L)
    r = np.asarray(r)
    tau = np.asarray(tau)
    tau_reward = np.asarray(tau_reward)
    visual_range = np.asarray(visual_range)
    gamma_damping = np.asarray(gamma_damping)
    eta_glow_damping = np.asarray(eta_glow_damping)
    turn_angle = np.asarray(turn_angle)

    learn_arr = np.asarray(is_learning, dtype=np.bool_)
    if learn_arr.ndim == 1:
        learn_cases = learn_arr.reshape(1, learn_arr.shape[0])
    elif learn_arr.ndim == 2:
        learn_cases = learn_arr
    else:
        raise ValueError("is_learning must be a 1D or 2D boolean array (or list/list-of-lists).")

    if learn_cases.shape[1] != num_agents:
        raise ValueError("Each is_learning case must have length num_agents.")

    return _run_collect_dict_ind_numba(
        episodes, time_ep,
        Nt, L, r, tau, tau_reward,
        num_agents, agent_step,
        visual_range, visual_angle,
        shared_depletion, visual_activated,
        num_actions, state_space,
        gamma_damping, eta_glow_damping,
        learn_cases,
        initial_h_0, h_0, g_update,
        policy_type, beta_softmax, max_no_H_update,
        upd_pos_method, turn_angle,
        n_run, ablation
    )

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #54bdabfe
@njit
def train_loop_collective_directions(episodes, time_ep, env, agents, max_counter,
                                      max_agents_directions, num_vals_directions,
                                      visual_activated=False, upd_pos_method='RND'):
    """
    EXP 6: Target-finding reward with (2 + max_agents_directions)-dimensional state.

    State = [counter, cone_index, dir_slot_0, ..., dir_slot_{max_agents_directions-1}]
    - counter: clipped step counter in [0, max_counter)
    - cone_index: 0 if no agent in cone, 1 if agents but none rewarded, 2 if rewarded agent in cone
    - dir_slot_k: 0 if no k-th closest agent in cone, else 1..num_vals_directions (discretized
                  relative direction with symmetric bins centered at 0, 2pi/n, 4pi/n, ...)

    Uses CollectiveDirectionsEnv (has get_directions_cone, agent_distances,
    upd_relative_directions, upd_agent_distances).
    state_space should be np.array([max_counter, 3] + [num_vals_directions+1]*max_agents_directions).
    """
    obs_size = 2 + max_agents_directions
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    # Fixed-size buffers for in-cone agent collection (max size = num_agents)
    cone_buf_idx = np.empty(agents.num_agents, dtype=np.int64)
    cone_buf_dist = np.empty(agents.num_agents, dtype=np.float64)
    taken = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()

        for t in range(time_ep):
            agents.increment_counters()

            # --- Build observations ---
            # 1) Counter (clipped)
            counters = np.minimum(agents.get_state().copy(), np.int64(max_counter - 1))

            # 2) Cone index and direction slots 
            cone_index = np.zeros(agents.num_agents, dtype=np.float64)
            directions_obs = np.zeros((agents.num_agents, max_agents_directions), dtype=np.float64)

            if visual_activated:
                directions_in_cone = env.get_directions_cone()  # (num_agents, num_agents), -1 if not in cone

                for i in range(agents.num_agents):
                    # Collect agents in cone into fixed buffers
                    num_in_cone = 0
                    for j in range(agents.num_agents):
                        if directions_in_cone[i, j] != -1.0:
                            cone_buf_idx[num_in_cone] = j
                            cone_buf_dist[num_in_cone] = env.agent_distances[i, j]
                            num_in_cone += 1

                    if num_in_cone > 0:
                        # cone_index: 1 if agents in cone, 2 if at least one is rewarded
                        has_rewarded = False
                        for k in range(num_in_cone):
                            if env.rewarded_agents[cone_buf_idx[k]] == 1:
                                has_rewarded = True
                                break
                        cone_index[i] = 2.0 if has_rewarded else 1.0

                        # Select closest max_agents_directions agents (partial selection sort)
                        num_take = num_in_cone if num_in_cone < max_agents_directions else max_agents_directions
                        for k in range(num_in_cone):
                            taken[k] = False
                        for s in range(num_take):
                            min_dist = 1e18
                            min_k = 0
                            for k in range(num_in_cone):
                                if not taken[k] and cone_buf_dist[k] < min_dist:
                                    min_dist = cone_buf_dist[k]
                                    min_k = k
                            taken[min_k] = True
                            j = cone_buf_idx[min_k]
                            # Symmetric bins: bin k covers [(2k-1)pi/n, (2k+1)pi/n], centered at 2k*pi/n
                            angle = directions_in_cone[i, j]
                            bin_idx = int(np.floor(angle * num_vals_directions / (2.0 * np.pi) + 0.5)) % num_vals_directions
                            directions_obs[i, s] = float(bin_idx + 1)  # +1: 0 reserved for "no agent"

            # observations shape: (num_agents, 2 + max_agents_directions)
            observations = np.empty((agents.num_agents, obs_size), dtype=np.float64)
            observations[:, 0] = counters.astype(np.float64)
            observations[:, 1] = cone_index
            observations[:, 2:] = directions_obs

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset counter BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step
            if upd_pos_method == 'RND':
                rewards = env.step(actions == 1)
            elif upd_pos_method == 'LR':
                rewards = env.step(actions)

            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1

    return save_rewards, agents.h_matrix


# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #70e90cb8
from .environments import CollectiveDirectionsEnv

@njit(parallel=True)
def run_collective_directions(episodes, time_ep,
             parallel_runs=4,      # number of runs executed in parallel via prange
             num_parallel_runs=1,  # number of times the parallel loop is repeated sequentially
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated=True,
             # Agent props
             num_actions=2,
             max_counter=50,
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method='RND',
             turn_angle=np.pi/4,
             max_agents_directions=2,
             num_vals_directions=4,
             ):
    """
    Parallel launcher for collective training with direction observations.

    Observation = [counter, cone_index, dir_slot_0, ..., dir_slot_{max_agents_directions-1}]
    - cone_index: 0=no agent in cone, 1=agents but none rewarded, 2=rewarded agent in cone
    - dir_slot_k: 0=no k-th closest agent in cone, 1..num_vals_directions=discretized relative direction

    state_space is built internally:
        [max_counter, 3, num_vals_directions+1, ..., num_vals_directions+1]
        with max_agents_directions repetitions of (num_vals_directions+1).

    Total runs = parallel_runs * num_parallel_runs.
    The outer loop (num_parallel_runs) is sequential; the inner loop (parallel_runs) runs in parallel.
    """
    # Build state_space from parameters
    state_space = np.empty(2 + max_agents_directions, dtype=np.int64)
    state_space[0] = max_counter
    state_space[1] = 3
    for k in range(max_agents_directions):
        state_space[2 + k] = num_vals_directions + 1

    total_runs = parallel_runs * num_parallel_runs
    save_h_matrix = np.zeros((total_runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((total_runs, num_agents, episodes))

    for outer in range(num_parallel_runs):
        for rep in prange(parallel_runs):
            n_run = outer * parallel_runs + rep
            agents = Foragers_efficient(
                num_agents, num_actions, state_space,
                gamma_damping, eta_glow_damping, policy_type, beta_softmax,
                initial_h_0, h_0, g_update, max_no_H_update,
            )
            env = CollectiveDirectionsEnv(num_agents, Nt, L, r, tau, agent_step,
                                          visual_range, visual_angle, shared_depletion,
                                          tau_reward, upd_pos_method, turn_angle)

            rews, mat = train_loop_collective_directions(
                episodes, time_ep, env, agents, max_counter,
                max_agents_directions, num_vals_directions,
                visual_activated, upd_pos_method
            )

            for t in range(episodes):
                save_rewards[n_run, :, t] = rews[:, t]
            save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix


# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #8153a6fc
@njit
def train_loop_follow_directions(episodes, time_ep, env, agents,
                                  max_agents_directions, num_vals_directions,
                                  visual_activated=False, upd_pos_method='RND'):
    """
    Follow-the-neighbor reward with max_agents_directions-dimensional state.

    State = [dir_slot_0, ..., dir_slot_{max_agents_directions-1}]
    - dir_slot_k: 0 if no k-th closest agent in cone, else 1..num_vals_directions
      (discretized relative direction, symmetric bins centered at 0, 2pi/n, 4pi/n, ...)

    Reward = 1 if any agent is in the visual cone (cone_index >= 1), 0 otherwise.
    Incentivizes agents to keep others in their visual cone, i.e., to follow each other.

    Uses CollectiveDirectionsEnv (get_directions_cone, agent_distances).
    state_space should be np.array([num_vals_directions+1]*max_agents_directions).
    """
    obs_size = max_agents_directions
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    # Fixed-size buffers for in-cone agent collection (max size = num_agents)
    cone_buf_idx = np.empty(agents.num_agents, dtype=np.int64)
    cone_buf_dist = np.empty(agents.num_agents, dtype=np.float64)
    taken = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()

        for t in range(time_ep):
            agents.increment_counters()  # required by Foragers_efficient for lazy H/G updates

            # --- Build observations (direction slots only; no counter, no cone_index) ---
            cone_index = np.zeros(agents.num_agents, dtype=np.float64)
            directions_obs = np.zeros((agents.num_agents, max_agents_directions), dtype=np.float64)

            if visual_activated:
                directions_in_cone = env.get_directions_cone()  # (num_agents, num_agents), -1 if not in cone

                for i in range(agents.num_agents):
                    num_in_cone = 0
                    for j in range(agents.num_agents):
                        if directions_in_cone[i, j] != -1.0:
                            cone_buf_idx[num_in_cone] = j
                            cone_buf_dist[num_in_cone] = env.agent_distances[i, j]
                            num_in_cone += 1

                    if num_in_cone > 0:
                        # cone_index still computed (used for reward below)
                        has_rewarded = False
                        for k in range(num_in_cone):
                            if env.rewarded_agents[cone_buf_idx[k]] == 1:
                                has_rewarded = True
                                break
                        cone_index[i] = 2.0 if has_rewarded else 1.0

                        # Select closest max_agents_directions agents (partial selection sort)
                        num_take = num_in_cone if num_in_cone < max_agents_directions else max_agents_directions
                        for k in range(num_in_cone):
                            taken[k] = False
                        for s in range(num_take):
                            min_dist = 1e18
                            min_k = 0
                            for k in range(num_in_cone):
                                if not taken[k] and cone_buf_dist[k] < min_dist:
                                    min_dist = cone_buf_dist[k]
                                    min_k = k
                            taken[min_k] = True
                            j = cone_buf_idx[min_k]
                            # Symmetric bins: bin k covers [(2k-1)pi/n, (2k+1)pi/n], centered at 2k*pi/n
                            angle = directions_in_cone[i, j]
                            bin_idx = int(np.floor(angle * num_vals_directions / (2.0 * np.pi) + 0.5)) % num_vals_directions
                            directions_obs[i, s] = float(bin_idx + 1)  # +1: 0 reserved for "no agent"

            # observations: direction slots only
            observations = np.empty((agents.num_agents, obs_size), dtype=np.float64)
            observations[:, :] = directions_obs

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset state BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step (updates positions; its return value is discarded)
            if upd_pos_method == 'RND':
                env.step(actions == 1)
            elif upd_pos_method == 'LR':
                env.step(actions)

            # Reward: 1 if any other agent is in the visual cone (cone_index 1 or 2)
            rewards = np.where(cone_index >= 1.0, 1.0, 0.0)
            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1

    return save_rewards, agents.h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #8d2c2990
from .environments import CollectiveDirectionsEnv

@njit(parallel=True)
def run_follow_directions(episodes, time_ep,
             parallel_runs=4,      # number of runs executed in parallel via prange
             num_parallel_runs=1,  # number of times the parallel loop is repeated sequentially
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=10,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated=True,
             # Agent props
             num_actions=2,
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method='RND',
             turn_angle=np.pi/4,
             max_agents_directions=2,
             num_vals_directions=4,
             ):
    """
    Parallel launcher for follow-the-neighbor training with direction-only observations.

    Observation = [dir_slot_0, ..., dir_slot_{max_agents_directions-1}]
    Reward = 1 if any agent is in the visual cone (cone_index 1 or 2).

    state_space is built internally:
        [num_vals_directions+1, ..., num_vals_directions+1]  (max_agents_directions entries)

    Total runs = parallel_runs * num_parallel_runs.
    The outer loop (num_parallel_runs) is sequential; the inner loop (parallel_runs) runs in parallel.
    """
    # Build state_space from parameters (no counter, no cone_index dimension)
    state_space = np.empty(max_agents_directions, dtype=np.int64)
    for k in range(max_agents_directions):
        state_space[k] = num_vals_directions + 1

    total_runs = parallel_runs * num_parallel_runs
    save_h_matrix = np.zeros((total_runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((total_runs, num_agents, episodes))

    for outer in range(num_parallel_runs):
        for rep in prange(parallel_runs):
            n_run = outer * parallel_runs + rep
            agents = Foragers_efficient(
                num_agents, num_actions, state_space,
                gamma_damping, eta_glow_damping, policy_type, beta_softmax,
                initial_h_0, h_0, g_update, max_no_H_update,
            )
            env = CollectiveDirectionsEnv(num_agents, Nt, L, r, tau, agent_step,
                                          visual_range, visual_angle, shared_depletion,
                                          tau_reward, upd_pos_method, turn_angle)

            rews, mat = train_loop_follow_directions(
                episodes, time_ep, env, agents,
                max_agents_directions, num_vals_directions,
                visual_activated, upd_pos_method
            )

            for t in range(episodes):
                save_rewards[n_run, :, t] = rews[:, t]
            save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #37aae821
@njit
def train_loop_collective_target_visual(episodes, time_ep, env, agents, max_counter, visual_activated = False, upd_pos_method = 'RND', ablation = None,
             no_learning = False):
    """
    Training loop for multiple agents in a 2D environment with collective behavior.

    Parameters
    ----------
    episodes : int
        Number of episodes to run.
    time_ep : int
        Number of time steps per episode.
    env : ResetEnv_2D
        The environment in which the agents operate.
    agents : Foragers_efficient
        The agents that will interact with the environment.
    max_counter : int
        The maximum value for the agents' counters.
    visual_activated : bool, optional
        Whether visual perception is activated for the agents. Default is False.
    upd_pos_method : str, optional
        The method for updating agent positions ('RND' or 'LR'). Default is 'RND'.
    ablation : str, optional
        If 'non_r', the non-rewarded agent state is always kept at 0. If 'r', the rewarded agent state is always kept at 0. Default is None.
    no_learning : bool, optional
        If True, agents will not learn from rewards. Default is False.

    """
    save_rewards = np.zeros((agents.num_agents, episodes))
    agents_rewarded = np.zeros(agents.num_agents, dtype=np.bool_)

    for ep in range(episodes):
        env.init_env()
        agents.agent_states = np.zeros_like(agents.agent_states)
        agents.reset_g()
        
        # Debugging
        # positions = np.zeros((time_ep, env.num_agents, 2))

        for t in range(time_ep):
            agents.increment_counters()

            # --- Build observations ---
            # 1) Counter (clipped)
            counters = np.minimum(agents.get_state().copy(), np.int64(max_counter - 1))

            # 2) Cone features
            if visual_activated:
                _, agents_spot = env.agents_in_cone()           


            # any_agent_in_cone: 1 if row sum > 0
            any_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated and ablation != 'non_r':
                for i in range(agents.num_agents):
                    if agents_spot[i].sum() > 0:
                        any_in_cone[i] = 1.0

            # rewarded_agent_in_cone: 1 if any agent with rewarded_agents==1 is in cone
            rewarded_in_cone = np.zeros(agents.num_agents, dtype=np.float64)
            if visual_activated and ablation != 'r':
                for i in range(agents.num_agents):
                    for j in range(env.total_agents):
                        if agents_spot[i, j] == 1 and env.rewarded_agents[j] == 1:
                            rewarded_in_cone[i] = 1.0
                            break

            # observations shape: (num_agents, 3)
            observations = np.empty((agents.num_agents, 3), dtype=np.float64)
            observations[:, 0] = counters.astype(np.float64)
            observations[:, 1] = any_in_cone
            observations[:, 2] = rewarded_in_cone

            actions = agents.deliberate(observations)

            # Post-reward step: force turn + reset counter BEFORE act
            actions[agents_rewarded] = 1
            agents.agent_states[agents_rewarded] = 0

            agents.act(actions)

            # Environment step
            if upd_pos_method == 'RND':
                env.update_pos(actions == 1)
            elif upd_pos_method == 'LR':
                env.update_pos(actions)                
            env.check_bc()
            env.update_target_state()
            env.update_rewarded_agents()

            rewards = env.check_encounter()
            rewards[agents_rewarded] = 0  # suppress double reward

            save_rewards[:, ep] += rewards
            if not no_learning:
                agents._learn_post_reward(rewards)

            agents_rewarded = rewards == 1
        
        # Debugging
        #     positions[t] = env.positions
        # for p in positions.transpose(1, 0, 2):
        #     plt.plot(p[:, 0], p[:, 1], '-')
        # plt.show()

    return save_rewards, agents.h_matrix

# %% ../../../nbs/lib_nbs/12_agents_numba.ipynb #7a605064
from .environments import CollectiveEnv_target_visual

@njit(parallel=True)
def run_collective_target_visual(episodes, time_ep, runs,
             # Environment props
             Nt=100,
             L=100,
             r=0.5,
             tau=5,
             tau_reward=1,
             num_agents=1,
             agent_step=1,
             visual_range=2.0,
             visual_angle=np.pi / 2,
             shared_depletion=True,
             visual_activated = True,
             # Agent props
             num_actions=2,
             state_space=np.array([50, 2, 2]),
             gamma_damping=0.00001,
             eta_glow_damping=0.1,
             initial_h_0=False,
             h_0=np.zeros((1, 2, 200)),
             g_update='s',
             policy_type='standard',
             beta_softmax=3,
             max_no_H_update=int(1e3),
             upd_pos_method = 'RND', # Method to update position. 'RND' for random angle turns, 'LR' for left/right turns.
             turn_angle = np.pi/4, # Angle for left/right turns if upd_pos_method is 'LR'.
             ablation = None,
             no_learning = False
             ):
    """
    Parallel launcher for collective training, where visual features are 
    if yes/no seeing an agent in front and if yes/no seeing a rewarded agent in front:
    
    state_space = np.array([max_counter, 2, 2])
    """

    assert num_agents == 1, "CollectiveEnv_target_visual is designed for a single agent (num_agents=1)."

    save_h_matrix = np.zeros((runs, num_agents, num_actions, state_space.prod()))
    save_rewards = np.zeros((runs, num_agents, episodes))

    for n_run in prange(runs):
        agents = Foragers_efficient(
            num_agents, num_actions, state_space,
            gamma_damping, eta_glow_damping, policy_type, beta_softmax,
            initial_h_0, h_0, g_update, max_no_H_update,
        )
        env = CollectiveEnv_target_visual(num_agents, Nt, L, r, tau, agent_step,
                                          visual_range, visual_angle, shared_depletion, 
                                          tau_reward, upd_pos_method, turn_angle)

        rews, mat = train_loop_collective_target_visual(episodes, time_ep, env, agents, state_space[0], 
                                                        visual_activated, upd_pos_method, ablation, no_learning)

        for t in range(episodes):
            save_rewards[n_run, :, t] = rews[:, t]
        save_h_matrix[n_run] = mat

    return save_rewards, save_h_matrix
